metaplex-foundation/metaplex-program-library

auction/js/src/accounts/Auction.ts
auction/js/src/accounts/BidderPot.ts
auction/js/src/transactions/CreateAuctionV2.ts
core/js/src/accounts/Account.ts
core/js/src/errors.ts
metaplex/js/src/MetaplexProgram.ts
metaplex/js/src/accounts/StoreConfig.ts
metaplex/js/src/mpl-metaplex.ts
metaplex/js/src/transactions/RedeemPrintingV2Bid.ts
metaplex/js/src/transactions/SetStoreV2.ts
metaplex/js/src/transactions/index.ts
token-vault/js/src/accounts/Vault.ts
token-vault/js/src/transactions/AddTokenToInactiveVault.ts
token-vault/js/src/transactions/UpdateExternalPriceAccount.ts

Porting all changes `248b61b..a844efe` that were applied to `program` folders and to modules
that are inside `mpl-core`.

chore: port SDK changes

---

.github/workflows/integration-token-metadata.yml
.github/workflows/program-auction-house.yml
.github/workflows/program-auction.yml
.github/workflows/program-metaplex.yml
.github/workflows/program-nft-packs.yml
.github/workflows/program-token-metadata.yml
.github/workflows/program-token-vault.yml
.github/workflows/sdk-auction-house.yml
.github/workflows/sdk-auction.yml
.github/workflows/sdk-core.yml
.github/workflows/sdk-metaplex.yml
.github/workflows/sdk-token-metadata.yml
.github/workflows/sdk-token-vault.yml

Problem:
All the checks run allways
Solution: 
Make them conditional

(feat) make actions contitional on the path that changed +core

---

Cargo.lock
nft-candy-machine/program/Cargo.toml

Fix BorshIo Error in mint_one_token caused by Anchor v0.20.0

revert to anchor v0.19.0

---

nft-candy-machine/program/src/lib.rs

Retrieves the gateway token `expire_time` before the call to `verify_and_expire_token`. The `verify_and_expire_token` instruction updates the expire time of the token, giving the impression that the token was created at the same time as the transaction is being processed.

Fixed gateway token expire time test

---

Cargo.lock
auction/program/Cargo.toml
auction/program/src/errors.rs
auction/program/src/lib.rs
auction/program/src/processor/cancel_bid.rs
auction/program/src/processor/place_bid.rs
auction/program/src/utils.rs
auction/program/tests/helpers.rs
auction/program/tests/lib.rs
core/rust/testing-utils/src/lib.rs

- (fix) test confirming exploit
- (fix) test confirmin fixed exploit

pda bidder pot

---

.github/workflows/integration-membership-token.yml
Cargo.lock

The integ tests were not being run for membership token
Add a gh workflow to run them on PR to master

(chore) add integ and update lock

---

.github/workflows/integration-membership-token.yml
membership-token/js/src/instructions/createMarket.ts
membership-token/js/src/instructions/createStore.ts
membership-token/js/src/utils/index.ts
membership-token/js/test/create-market.test.ts
membership-token/js/test/create-store.test.ts
membership-token/js/test/transactions/create-market.ts
membership-token/js/test/transactions/create-store.ts
membership-token/js/test/transactions/init-selling-resouce.ts
membership-token/js/test/utils/index.ts

* update create store instruction (js)
* update tests for Store account (js)
* add create market instruction (js)
* add tests for Market account (js)

Add createMarket instruction, tests (js)

---

Cargo.lock
token-vault/program/Cargo.toml
token-vault/program/README.md

Prepares `token-vault` for publishing.

update token-vault for publishing

---

candy-machine/program/README.md

Last missing piece for version 2.0.1.

add readme to candy-machine package

---

.github/workflows/program-membership-token.yml

Prevents membership-token program CI from running unless its related files change.
closes #162

chore: add "changes" filter to membership-token program CI

---

auction-house/program/src/lib.rs
auction-house/program/tests/buy.rs
auction-house/program/tests/cancel.rs
auction-house/program/tests/deposit.rs
auction-house/program/tests/execute_sell.rs
auction-house/program/tests/sell.rs
auction-house/program/tests/utils/setup_functions.rs

Adds more tests and cleanup to AH code.
- (test) add buy test
- (test) happy path cases

auction house tests

---

fixed-price-sale/program/src/lib.rs
fixed-price-sale/program/tests/claim_resource.rs

- Fixed critical bug in 'ClaimResource' instruction, that revert transaction if user use native SOL

fix: added native SOL support to 'ClaimResource' instruction.

---

nft-packs/program/src/processor/init_pack.rs
nft-packs/program/src/processor/request_card_to_redeem.rs
nft-packs/program/src/utils.rs
nft-packs/program/tests/activate.rs
nft-packs/program/tests/deactivate.rs
nft-packs/program/tests/init_pack_set.rs
nft-packs/program/tests/transfer_pack_authority.rs

Added check for valid `SlotHash` in `RequestCardToRedeem` instruction.

fix: added 'SlotHash' sysvar check in 'RequestCardToRedeem' instruction, rust fmt.

---

token-metadata/Cargo.lock
token-metadata/js/package.json
token-metadata/js/src/transactions/RevokeCollectionAuthority.ts
token-metadata/program/Cargo.toml
token-metadata/program/src/instruction.rs
token-metadata/program/src/processor.rs
token-metadata/program/tests/verify_collection.rs

add missing account to revoke_collection_authority instruction

fix(token-metadata): add missing account

---

auction-house/program/Cargo.lock
auction-house/program/tests/buy.rs
auction-house/program/tests/cancel.rs
auction-house/program/tests/create_auction_house.rs
auction-house/program/tests/deposit.rs
auction-house/program/tests/execute_sell.rs
auction-house/program/tests/sell.rs

Clean up test linting issues so I don't go insane.

refactor(auction-house): fix test lint issues

---

auction-house/program/Cargo.toml
auction-house/program/src/lib.rs
auction-house/program/src/receipt/mod.rs

ALREADY ON CHAIN
(fix) adds assertion for reciepts to ensure proper safeguards.

Reciepts PDA assertions Addition

---

fixed-price-sale/js/package-lock.json
fixed-price-sale/js/package.json
yarn.lock

Fixes issues that came after package updates.
https://github.com/solana-labs/solana-program-library/issues/2683
https://github.com/solana-labs/wallet-adapter/issues/265#issuecomment-1025285873

fix: fixed-price-sale broken packages

---

token-metadata/js/package.json
token-metadata/program/src/assertions/uses.rs
token-metadata/program/src/error.rs
token-metadata/program/src/processor.rs
token-metadata/program/tests/bump_seed_migration.rs
token-metadata/program/tests/freeze_delegated_account.rs
token-metadata/program/tests/revoke_use_authority.rs
token-metadata/program/tests/seralization.rs
token-metadata/program/tests/sign_metadata.rs
token-metadata/program/tests/update_metadata_account_v2.rs
token-metadata/program/tests/uses.rs
token-metadata/program/tests/utils/edition_marker.rs
token-metadata/program/tests/utils/external_price.rs
token-metadata/program/tests/utils/master_edition_v2.rs
token-metadata/program/tests/utils/metadata.rs
token-metadata/program/tests/verify_collection.rs

Already deployed as it was security patch

Scan result fixes

---

token-entangler/program/src/lib.rs
token-entangler/program/src/utils.rs

This reverts commit af62203af0a31e82dfb4fb841db2c0ae8d62a666.
Unclear on why this change broke existing entanglements, but recommending we revert and investigate since there's nothing currently entangled that requires the new functionality this introduced

Revert "Entangle full supply (#317)"

---

candy-machine/program/src/lib.rs

Fixes branching logic to enable the candy machine to change its collection even if the prior collection hasn't been removed.

Allow setting candy machine collection without removing prior collection

---

candy-machine/program/src/lib.rs

Before this PR a clever malicious user could have added another instruction after Set Collection or After Mint that could fail the TXN avoiding the bot fee. Since we were not completing the entire transaction the compute is fairly cheap and no NFTs could be mints. Never less this could be used to box people out right before a mint without any penalty. Since there is no known way in solana to make a transaction succeed but also halt the execution of the next instructions. Since we cannot effectively charge a bot for this case we will immediately fail the transaction to avoid any additional or malicious compute the attacker may add to their custom program

Fail cheaply for extra IX

---

candy-machine/program/src/constants.rs
candy-machine/program/src/lib.rs
candy-machine/program/src/processor/mint.rs

@austbot Summary
Cupcake is a cool new program built by @bhgames and @bartosz-lipinski  it allows use of candy machine, via a nfc and mobile mint link. This integration will grow candy machine usage and is net good for the protocol and candy machine users.

Add cupcake to the list

---

.github/CODEOWNERS

Summary: Move ownership to per folder so we can more easily support community contribution

folder based ownership

---

auctioneer/program/Cargo.lock
auctioneer/program/src/errors.rs
auctioneer/program/src/lib.rs
auctioneer/program/src/sell/config.rs
auctioneer/program/src/sell/mod.rs
auctioneer/program/src/utils.rs
auctioneer/program/tests/buy.rs
auctioneer/program/tests/cancel.rs
auctioneer/program/tests/close_escrow_account.rs
auctioneer/program/tests/common/mod.rs
auctioneer/program/tests/deposit.rs
auctioneer/program/tests/execute_sale.rs
auctioneer/program/tests/sell.rs
auctioneer/program/tests/utils/setup_functions.rs
auctioneer/program/tests/withdraw.rs

Adding bid increment option to Auctioneer example

---

candy-machine/program/src/errors.rs
candy-machine/program/src/processor/mint.rs
candy-machine/program/src/utils.rs

fix(candy-machine): fixing output for bot tax

---

candy-machine/js/idl/candy_machine.json
candy-machine/program/Cargo.lock
candy-machine/program/Cargo.toml
candy-machine/program/src/lib.rs

This PR is for testing our branch upshing and versioning automation
Please approve review with a comment of "version patch"

Bump CM Version

---

auction-house/js/idl/auction_house.json
auction-house/program/Cargo.lock
auction-house/program/Cargo.toml
auction-house/program/src/pda.rs

Bumping Auction House to v1.2.4

---

auction-house/program/src/state.rs
auction-house/program/src/utils.rs
auctioneer/program/tests/execute_sale.rs

Clippy and cargo fmt fixes with new version of rustc 1.63.0.

Fix linting issues for Auction House and Auctioneer

---

token-metadata/program/src/processor.rs

refactor(token-metadata): fix typo in processor.rs

---

candy-machine/js/idl/candy_machine.json
candy-machine/program/Cargo.lock
candy-machine/program/Cargo.toml
candy-machine/program/src/processor/mint.rs
candy-machine/program/tests/mint.rs
candy-machine/program/tests/utils/helper_transactions.rs

This must be the first check before any bot taxes to fail the transaction

move metadata check to the top

---

token-metadata/js/README.md

Update Token Metadata README.md

---

candy-guard/program/src/errors.rs
candy-guard/program/src/guards/mod.rs
candy-guard/program/src/guards/nft_payment.rs
candy-guard/program/src/instructions/mint.rs
candy-guard/program/src/state/candy_guard.rs
candy-guard/program/src/utils.rs

Im not 100% sure moving the expected account indicies around makes alot of sense here but this is babys first guard. Even though I designed this architecture I have not written a guard yet  :)
In general guards need to be isolated so I I need to consider absolute or global account pointers this implementation of the candy guard design will quickly become hard to maintain
Never the less this is my first attempt at making a guard under this implementation

Nft Collection Guard First Crack

---

bubblegum/program/Cargo.toml

This pr preps bubblegum for publishing

Publish BubbleGum to Crates

---

bubblegum/program/Cargo.lock
bubblegum/program/Cargo.toml
bubblegum/program/src/lib.rs
bubblegum/program/src/state/leaf_schema.rs
bubblegum/program/src/utils.rs

We need to use the correct crates in order to publish this. Thjis pr fixes that .

Prep for Publishing MPL Bubblegum 

---

Cargo.lock
candy-machine-core/program/Cargo.toml
candy-machine-core/program/src/instructions/mint.rs

due to dependency hell which it seems I am mired in even though being a religious and spiritual man, removing anchor-spl proivides a tiny ra of hope to a dammned world of blockbuster the indexer

Remove anchor spl

---

candy-machine/js/idl/candy_machine.json
candy-machine/js/src/generated/instructions/unlockFunds.ts
candy-machine/program/src/processor/freeze/unlock_funds.rs

Added anchor `/// CHECK:` on wallet account.

fix: add check on wallet account

---

bubblegum/program/Cargo.lock
bubblegum/program/Cargo.toml
bubblegum/program/src/state/metaplex_anchor.rs

Dependency hell this is needed to get me out of purgatory

Update To newest token Metadata

---

token-metadata/program/src/state.rs

This PR just adds the FromPrimitive traits to another enum for use in the off chain client world

Adds From Traits for easier use in offchain applications

---

bubblegum/js/package.json
bubblegum/js/src/mpl-bubblegum.ts
bubblegum/js/tests/main.test.ts
package.json
yarn.lock

Replace hard coded tree-size by calculating account size with `@solana/spl-account-compression`

Bubblegum: use @solana/spl-account-compression

---

bubblegum/js/typedoc.json

This will make the page have a better layour.

Improve layout of JS SDK generated typedocs

---

trifle/Cargo.lock
trifle/cli/src/helpers/trifle.ts
trifle/cli/tokens.json
trifle/js/idl/mpl_trifle.json
trifle/js/package.json
trifle/js/src/generated/accounts/EscrowConstraintModel.ts
trifle/js/src/generated/accounts/Trifle.ts
trifle/js/src/generated/instructions/TransferIn.ts
trifle/js/src/generated/instructions/TransferOut.ts
trifle/program/Cargo.toml
trifle/program/src/instruction.rs
trifle/program/src/processor.rs
trifle/program/tests/trifle.rs
yarn.lock

Using the new `#[default_optional_accounts]` macro from Shank and new version of Solita to generate JS SDK.

Default Optional Accounts

---

trifle/program/src/instruction.rs
trifle/program/src/processor.rs
trifle/program/src/state/escrow_constraints.rs
trifle/program/src/state/trifle.rs
trifle/program/src/tests/state.rs
trifle/program/tests/trifle.rs

Reverts metaplex-foundation/metaplex-program-library#865

Revert "Add bump seeds to Trifle Program Accounts"

---

candy-machine-core/js/test/add-config-lines.test.ts
candy-machine-core/js/test/mint.test.ts
candy-machine-core/js/test/setup/txs-init.ts
candy-machine-core/program/src/instructions/add_config_lines.rs
candy-machine-core/program/src/state/candy_machine.rs
candy-machine/program/src/processor/add_config_lines.rs
candy-machine/program/src/processor/collection/set_collection_during_mint.rs
candy-machine/program/src/processor/freeze/remove_freeze.rs
candy-machine/program/src/processor/freeze/thaw_nft.rs
candy-machine/program/src/processor/mint.rs
candy-machine/program/src/processor/withdraw.rs
candy-machine/program/src/state.rs
candy-machine/program/tests/collection.rs
candy-machine/program/tests/core/helpers.rs
candy-machine/program/tests/core/master_edition_manager.rs
candy-machine/program/tests/core/metadata_manager.rs
candy-machine/program/tests/freeze.rs
candy-machine/program/tests/initialize.rs
candy-machine/program/tests/mint.rs
candy-machine/program/tests/update.rs
candy-machine/program/tests/utils/candy_manager.rs
candy-machine/program/tests/utils/configs.rs

Add check to validate the config lines range.

Add index check to add_config_lines

---

trifle/program/src/error.rs
trifle/program/src/processor.rs

Improving the way we validate collections

Trifle collections validation fix

---

candy-machine/js/idl/candy_machine.json
candy-machine/js/package.json
candy-machine/js/src/generated/accounts/CandyMachine.ts
candy-machine/js/src/generated/accounts/CollectionPDA.ts
candy-machine/js/src/generated/accounts/FreezePDA.ts
candy-machine/js/src/generated/instructions/addConfigLines.ts
candy-machine/js/src/generated/instructions/initializeCandyMachine.ts
candy-machine/js/src/generated/instructions/mintNft.ts
candy-machine/js/src/generated/instructions/removeCollection.ts
candy-machine/js/src/generated/instructions/removeFreeze.ts
candy-machine/js/src/generated/instructions/setCollection.ts
candy-machine/js/src/generated/instructions/setCollectionDuringMint.ts
candy-machine/js/src/generated/instructions/setFreeze.ts
candy-machine/js/src/generated/instructions/thawNft.ts
candy-machine/js/src/generated/instructions/unlockFunds.ts
candy-machine/js/src/generated/instructions/updateAuthority.ts
candy-machine/js/src/generated/instructions/updateCandyMachine.ts
candy-machine/js/src/generated/instructions/withdrawFunds.ts
candy-machine/program/Cargo.lock
candy-machine/program/Cargo.toml

This pr bumps versions from a recently patched security exploit.

Bump cmv2 versions

---

token-metadata/program/src/processor/burn/burn_nft.rs
token-metadata/program/tests/burn_nft.rs

Fix: enable burning collection items with burned parents

---

token-metadata/program/ProgrammableNFTGuide.md

This PR adds instructions to setup a local environment to run Token Metadata tests.

Add local setup instruction

---

token-metadata/program/src/state/programmable.rs

Currently the method to determine the authority type of a request has a fixed order. This does not work in all cases, since an address (authority) can match multiple authority types.
This PR adds a `precedence` field to the `AuthorityRequest` so the caller code can specify the order for the evaluation of the type. For example, passing the precedence `[AuthorityType::Metadata, AuthorityType::Delegate]` will make the evaluation to try to match the authority to the update authority; then it would try to match to a delegate.

Add precedence field to authority request

---

token-metadata/program/ProgrammableNFTGuide.md

Add `LockedTransfer` delegate details and updated package versions.

Add LockedTransfer delegate docs

---

.github/workflows/integration-reusable.yml
.github/workflows/integration.yml
token-metadata/js/test/setup/txs-init.ts
token-metadata/js/test/transfer.test.ts

This PR adds Token Metadata in the CI integration tests.

Add integration tests

---

token-metadata/program/src/processor/metadata/transfer.rs

This PR relaxes the token standard check on transfer.

Relax token standard check

---

token-metadata/program/ProgrammableNFTGuide.md

Also add Auth Rules, maybe its not needed in that guide.  If so I can remove auth rules from the guide.

Update version in pNFT guide

---

token-metadata/js/idl/mpl_token_metadata.json
token-metadata/js/src/generated/errors/index.ts
token-metadata/js/test/update.test.ts
token-metadata/program/src/processor/collection/verify_sized_collection_item.rs
token-metadata/program/src/processor/metadata/create.rs
token-metadata/program/src/processor/metadata/migrate.rs
token-metadata/program/src/processor/metadata/mint.rs
token-metadata/program/src/processor/metadata/transfer.rs
token-metadata/program/src/processor/metadata/update.rs
token-metadata/program/src/processor/mod.rs
token-metadata/program/src/utils/collection.rs
token-metadata/program/src/utils/mod.rs
token-metadata/program/src/utils/programmable_asset.rs
token-metadata/program/tests/burn_edition_nft.rs

Adding size reductions to token metadata in the form of abbreviated debug messages or removals where unnecessary.

Adding minor size optimizations

---

candy-machine/program/Cargo.lock
candy-machine/program/Cargo.toml

PR to update token metadata crate version.

Update token metadata dependency

---

token-metadata/program/src/state/metadata.rs
token-metadata/program/tests/update.rs

* Added `can_update_data_and_is_mutable_same_instruction` to test.
* Also added a few more tests to `Update` for other cases.
When adding the delegates the order was changed such that `is_immutable` was updated in the deserialized metadata struct before the immutability check was done.  This meant that you would no longer be able to update `data` at the same time as setting `is_immutable`.

Allow data and is_immutable to be updated at same time

---

token-metadata/program/src/processor/metadata/transfer.rs
token-metadata/program/tests/transfer.rs

This PR adds a check on the delegate of both source and destination token accounts when transferring `pNFT`s:
1. It clears the delegate of the source account when the holder transfer the token.
2. It prevents the transfer if the destination token account already has a delegate.

Add delegate check on transfer

---

hydra/program/Cargo.lock
hydra/program/Cargo.toml
hydra/program/src/processors/add_member/nft.rs
hydra/program/src/processors/add_member/wallet.rs
hydra/program/src/processors/distribute/wallet_member.rs
hydra/program/src/processors/init/init_for_mint.rs
hydra/program/src/processors/init/init_parent.rs
hydra/program/src/processors/mod.rs
hydra/program/src/processors/remove_member/process_remove_member.rs
hydra/program/src/processors/signing/sign_metadata.rs
hydra/program/src/processors/stake/set.rs
hydra/program/src/processors/stake/set_for.rs
hydra/program/src/processors/stake/unstake.rs
hydra/program/src/processors/transfer_shares/process_transfer_shares.rs
hydra/program/src/utils/logic/calculation.rs
hydra/program/src/utils/logic/distribution.rs
hydra/program/src/utils/logic/transfer.rs
hydra/program/src/utils/mod.rs
hydra/program/src/utils/validation/mod.rs

PR to bump hydra program version to the one that is currently deployed.

Bump hydra version

---

hydra/program/Cargo.lock
hydra/program/Cargo.toml

PR to fix the `solana-zk-token-sdk` dependency on hydra.

Fix dependency version

---

core/rust/utils/Cargo.lock
core/rust/utils/Cargo.toml
core/rust/utils/src/token/assertions.rs
core/rust/utils/src/token/cpi.rs
core/rust/utils/src/token/utils.rs

This PR adds support to SPL Token-2022.

Add Token-2022 support

---

core/rust/utils/Cargo.lock
core/rust/utils/Cargo.toml

PR to bump `spl-token-2022` crate version.

Bump spl-token-2022 version
