metaplex-foundation/metaplex-program-library

core/js/package.json
lerna.json
metaplex/js/package.json
package.json
token-metadata/js/package.json
token-vault/js/package.json

Using npm registry and using versions in `package.json` as basis to determine if new version of
a package needs to be published.

chore: configuring lerna publish

---

.np-config.js
README.md
auction/js/.np-config.js
auction/js/package.json
core/js/.np-config.js
core/js/package.json
metaplex/js/.np-config.js
metaplex/js/package.json
package.json
token-metadata/js/.np-config.js
token-metadata/js/package.json
token-vault/js/.np-config.js
token-vault/js/package.json
yarn.lock

This PR adds [np](https://github.com/sindresorhus/np) to manage versioning and publishing packages in
order to ensure that the package builds and all tests pass.
You have to be on an up to date `master` branch in order to perform that step (`np` will verify
that).
NOTE: that packages are versioned indepenently since contracts aren't necessarily coupled to
other contracts.
As part of that step proper git tags are generated and pushed. A commit with a proper commit
message is generated as well and pushed.
NOTE: that for history's sake it includes commits of other options, i.e. managing this manually via npm scripts, therefore it's best to view the final change set instead of individual commits.

chore: use np to orchestrate package versioning/publising

---

.np-config.js
README.md
auction/js/.np-config.js
auction/js/package.json
core/js/.np-config.js
core/js/package.json
metaplex/js/.np-config.js
metaplex/js/package.json
token-metadata/js/.np-config.js
token-metadata/js/package.json
token-vault/js/.np-config.js
token-vault/js/package.json
yarn.lock

When attempting to publish individual packages I realized that `np` doesn't play very well with
a monorepo containing multiple packages.
Therefore I switched to using npm scripts automatically invoked before/after
versioning/publishing in order to manage those tasks.
I did not add a check for clean master branch for now but added a big note to the readme that
all publishes should be performed from that branch.

chore: switching to npm scripts to manage version/publish

---

token-metadata/program/src/error.rs
token-metadata/program/src/instruction.rs
token-metadata/program/src/processor.rs
token-metadata/program/tests/update_metadata_account_v2.rs
token-metadata/program/tests/utils/metadata.rs
token-metadata/test/src/main.rs

Ported from [metaplex repo:](https://github.com/metaplex-foundation/metaplex/pull/984). 
> Currently there appears to be no way to set is_mutable to be false after an NFT metadata account has been created. Many NFTs, such as any created with default settings by candy_machine_cli, are created with the flag to true. It is desirable to have the ability to flip it to false at a later date, once any metadata issues are resolved or the community makes a decision to do so, etc.
I'll be looking at adding tests to this next before it gets merged. @thlorenz would like to discuss tests with you (it appears the tests for `token-metadata` are currently broken).

Allow is_mutable to be flipped false via update_metadata_accounts_v2

---

.github/workflows/program-token-vault.yml

Token Vault Program Checks didn't run even if changes were applied to it.
Each filter is `AND` and thus this was changed to have one filter per folder and `OR` them as
part of the query.

fix: token vault ci filter

---

core/rust/testing-utils/src/utils/metadata.rs
token-metadata/program/src/assertions/collection.rs
token-metadata/program/src/error.rs
token-metadata/program/src/instruction.rs
token-metadata/program/src/pda.rs
token-metadata/program/src/processor.rs
token-metadata/program/src/state.rs
token-metadata/program/src/utils.rs
token-metadata/program/tests/approve_use_authority.rs
token-metadata/program/tests/use.rs
token-metadata/program/tests/utils/metadata.rs
token-metadata/program/tests/verify_collection.rs

Closes #87 
Allows collection authority to be delegated to another key.

(feat) adds collection authority system

---

Cargo.lock
token-metadata/program/Cargo.toml
token-metadata/program/README.md
token-metadata/program/src/assertions/collection.rs
token-metadata/program/src/processor.rs

Prepares `token-metadata` v1.1.0 to be published on crates.io.

Publish token metadata

---

nft-candy-machine/program/src/lib.rs

Users are complaining ([see issue here](https://github.com/metaplex-foundation/metaplex/issues/1371)) about a lack of rent exemption when creating their Candy Machines. Opening this PR to start a discuss if we want to move forward with this change, if there are unknown security side effects or anything else we'd like to discuss before we go ahead, or reject, this change.
https://docs.rs/anchor-lang/0.18.0/anchor_lang/derive.Accounts.html
`Optional attribute to skip the rent exemption check. By default, all accounts marked with #[account(init)] will be rent exempt, and so this should rarely (if ever) be used. Similarly, omitting = skip will mark the account rent exempt.`

[Candy Machine v2] Adding rent exemption to CMv2 account creation

---

Cargo.lock
nft-candy-machine/program/Cargo.toml
nft-candy-machine/program/src/lib.rs

@febo in order to publish this as a crate I'm updating the `solana-gateway` lib from a git dependency to a versioned one on crates.io. This changes the `verify_gateway_token_account_info` to accept a `VerificationOptions` `Option` as you can see from the latest docs [here](https://docs.rs/solana-gateway/0.1.1/solana_gateway/struct.Gateway.html#method.verify_gateway_token_account_info). Passing in `None` uses the default options which I think is what we want, but it might make our time expired check redundant. Take a look when you get a chance and let me know if you have any questions.

prepare candy-machine for crate publishing

---

README.md

Add list of deployed Rust crates to README. Uses static link to crates.io latest version and Img Shield links so version updates automatically.

add deployed Rust crates to README

---

nft-packs/program/src/processor/request_card_to_redeem.rs

Problem: 
Spl token program now 0s the account data after closing the account which makes instructions and usage of the account post close fail 
Solution:
Move code that closes the account AFTER the usage of the data

(fix) spl_token account 0

---

token-metadata/Cargo.lock
token-metadata/program/Cargo.toml
token-metadata/program/src/assertions/collection.rs
token-metadata/program/src/assertions/uses.rs
token-metadata/program/src/instruction.rs
token-metadata/program/src/processor.rs
token-metadata/program/src/state.rs
token-metadata/program/tests/bump_seed_migration.rs

Existing UseAuthorityRecords would become unusable if  1.2.0 was shipped
#Solution
As a part of the 1.2.0 changes we identified a migration case we could accomplish to avoid breaking the 100s of use Authority records in the wild.
We did not implement this migration for the CollectionAuthority records as they are not in use yet

(fix) migrate bump seeds on UARs

---

token-metadata/program/src/error.rs
token-metadata/program/src/instruction.rs
token-metadata/program/src/processor.rs
token-metadata/program/src/utils.rs
token-metadata/program/tests/approve_use_authority.rs
token-metadata/program/tests/bump_seed_migration.rs
token-metadata/program/tests/create_master_edition.rs
token-metadata/program/tests/create_metadata_account.rs
token-metadata/program/tests/freeze_delegated_account.rs
token-metadata/program/tests/revoke_use_authority.rs
token-metadata/program/tests/update_metadata_account_v2.rs
token-metadata/program/tests/uses.rs
token-metadata/program/tests/utils/metadata.rs
token-metadata/program/tests/verify_collection.rs

https://github.com/metaplex-foundation/metaplex-program-library/pull/171
I had to re make the PR so I could fix it.
We have been building a protocol that enabled rentals for new tokens and were planning to try to enable this functionality for existing NFTs (whose freeze_authority is held by metaplex-token-metadata)
Our proposal is: freeze/unfreeze instructions that proxy instruction through to spl_token_program IF the signer is the delegate of the single token in the token_account that they are trying to freeze.
In other words, if someone delegated you the NFT in a token account, you can freeze that specific token account. Essentially this opens up a world of possibilities around conditional ownership, rentals, time-revoking tokens etc. where you as the holder can claim it but agree by …

Adds Freeze Authority

---

token-metadata/Cargo.lock
token-metadata/cli/Cargo.toml
token-metadata/cli/src/main.rs
token-metadata/program/Cargo.toml

1.2* packages were broken , 1.2.3 brings spl_token down to 3.2.0 as recommended by solana team

(fix) consumption of 1.2.* broken

---

metaplex/js/src/accounts/SafetyDepositConfig.ts
metaplex/js/src/transactions/ValidateSafetyDepositBoxV2.ts
metaplex/js/src/transactions/index.ts

- add `ValidateSafetyDepositBoxV2` instruction (needed for start auction)
- add schema for `SafetyDepositConfigData`, `ParticipationStateV2`, `ParticipationConfigV2`, `AmountRange`
- remove manual deserialize for `SafetyDepositConfigData`

feature: add ValidateSafetyDepositBoxV2 instruction

---

token-metadata/program/src/error.rs
token-metadata/program/src/utils.rs
token-metadata/program/tests/update_metadata_account_v2.rs

- Verified creators cannot be removed or shares reduced after the primary sale has happened.
- The seller fee basis points can not be adjusted after the primary sale.

Update Restrictions After Primary Sale

---

token-metadata/js/src/accounts/Metadata.ts

I've tested it with an account with 11 tokens and it's around 10-25 times faster than `findByOwnerV2`. Not sure if it's still faster with wallets that have way more tokens.
Here is the [benchmark file](https://gist.github.com/fersilva16/b34cc997e952d8c4d4573b5e30e24927).
Some results:
| findByOwnerV2  | findByOwnerV3 | Times faster |
| -------------- | ------------- | ------------ |
| `23.220s`      | `840.56ms`    | `26.62x`     |
| `16.619s`      | `1.586s`      | `9.47x`      |
| `15.926s`      | `1.604s`      | `8.92x`      |
| `20.315s`      | `969.688ms`   | `19.95x`     |
| `16.426s`      | `1.596s`      | `9.29x`      |
| `20.174s`      | `1.032s`      | `18.54x`     |

feat: add findByOwnerV3 method

---

fixed-price-sale/program/src/lib.rs

Fix in Buy instruction
Edition number in Buy instruction was calculated incorrect and instruction produced error when users try to sell the same NFT second time. Also because of this bug the wrong value was set for master edition supply
Now we calculate edition number like this `master_edition_supply + 1` instead of `selling_resource.supply`

Change edition number source in buy instruction

---

token-metadata/Cargo.lock
token-metadata/js/package.json
token-metadata/program/Cargo.toml
token-metadata/program/src/assertions/collection.rs
token-metadata/program/src/processor.rs
token-metadata/program/src/utils.rs
token-metadata/program/tests/mint_new_edition_from_master_edition_via_token.rs

Collections on Master Editions that are Verified were breaking Editions being minted
#Solution
Allow Creation Verification if the token standard is NonFungible Edition

fixes prints when collection is added

---

auction-house/js/idl/auction_house.json
auction-house/js/package.json
auction-house/js/src/generated/instructions/buy.ts
auction-house/program/Cargo.lock
auction-house/program/Cargo.toml
auction-house/program/src/bid/mod.rs

1.0.1 went to devnet with a mut where there shouldn't be , in my cli testing I found it and fixed that and another longstanding bug hidden in the layers of cli garbage https://github.com/metaplex-foundation/metaplex/pull/1847
This pr fixes that and bumps for publishing

(fix) idl and code gen

---

.github/workflows/program-fixed-price-sale.yml
.github/workflows/program-token-metadata.yml

Updating solana version for fixed prices sales tests to `1.9.9`. This is given the info that solana validator instability causes those tests to fail. There were some [stability changes](https://github.com/solana-labs/solana/releases) in the releases from `1.9.5  - 1.9.9`.
They [appear to be fixed now](https://github.com/metaplex-foundation/metaplex-program-library/runs/5360803661?check_suite_focus=true)

chore: repair broken fixed price sales tests

---

candy-machine/program/src/lib.rs

Change the remaining accounts logic to match existing conditionals on frontend. without this, whitelist token mints with presale and burntoken will fail if user has no presale whitelist token

fix 0xbba error with whitelist token mint

---

.github/workflows/integration-fixed-price-sale.yml

CI for this workflow is currently failing with:
```
The workflow is not valid. .github/workflows/integration-fixed-price-sale.yml (Line: 29, Col: 13): 
A sequence was not expected 
.github/workflows/integration-fixed-price-sale.yml (Line: 31, Col: 13):
A sequence was not expected
```
This PR fixes this and also makes sure that the build is triggered if the workflow file itself
changed.

fix: integration fixed price test workflow file syntax issue

---

auction-house/program/Cargo.lock
auction-house/program/Cargo.toml
auction-house/program/src/utils.rs

This PR replaces the `mpl-token-metadata` lib with the older version `metaplex-token-metadata` for importing the Metadata struct to avoid deserialization issues with NFTs that have corrupted metadata. 
There are a number of NFTs in the wild that have corrupted metadata in the "v2" metadata (fields after the `edition_nonce`). This causes issues with deserialization in client-side Rust tools and in Solana programs which use strict typing to do Borsh deserialization. 
I'm working on a long term fix, which requires a change to the `token-metadata` program, but that will take some time to implement. This is a very minimal change which will fix `auction-house`'s deserialization problems in the near term and which will be easy to roll back when the data is solved externally.

fix(auction-house): use metaplex-token-metadata lib for Metadata struct

---

fixed-price-sale/js/src/utils/index.ts

The findPayoutTicketAddress arguments were named incorrectly. This switches the names to match the PDA seeds. The function was already being called with the correct arguments.
lib.rs:
```
pub struct Withdraw<'info> {
...
#[account(mut, seeds=[PAYOUT_TICKET_PREFIX.as_bytes(), market.key().as_ref(), funder.key().as_ref()], bump=payout_ticket_bump)]
payout_ticket: UncheckedAccount<'info>,
```

fix: switch fixed-price-sale findPayoutTicketAddress arguments

---

.github/workflows/integration-token-vault.yml

Bumping version so PR validation can pass again.

Chore: Bump Token Vault integration test version to 1.9.14

---

candy-machine/js/package.json
candy-machine/js/src/errors.ts
candy-machine/js/src/generated/index.ts
candy-machine/js/src/mpl-candy-machine.ts
yarn.lock

- currently all hangs off `CandyMachineProgram` which makes less sense
since we also export types + classes here
- also this fixes the issues of `./generated/types` not being
exposed at all
- I kept `CandyMachineProgram` around for now, but ideally we'd remove
that as well and switch to the approach that token-metadata uses
- deps: add cusper dep
- api: expose errors and cusper based error API

chore: expose full API including errors

---

candy-machine/js/package.json
yarn.lock

- this is necessary to pull latest spl-token package as otherwise we
run into odd dependency resolution issues inside the js-next SDK

chore: update mpl-core package in candy machine SDK

---

fixed-price-sale/program/src/processor/claim_resource.rs
fixed-price-sale/program/src/processor/save_primary_metadata_creators.rs
fixed-price-sale/program/tests/buy.rs
fixed-price-sale/program/tests/claim_resource.rs

* Corrected match statement in `err_gated_unverified_nft`, that would
match on any `err_code`.
* Marked `primary_metadata_creators_bump` as unused in
`SavePrimaryMetadataCreators` to remove compile warning.
* Fixed other unused variable compiler warnings for program and tests.
* Testing: `cargo test-bpf --bpf-out-dir ../../target/deploy` passes,
although even before this change, sometimes some buy tests will time
out.

Fixing test in fixed-price-sale

---

Cargo.lock
token-entangler/program/Cargo.toml
token-entangler/program/src/lib.rs
token-entangler/program/tests/entangler_lifecycle_test.rs

The token-entangler is on the struggle-bus -- in particular, the create entanglement instruction fails frequently. I'm not sure what the root cause is yet, but this fork contains a test that reproduces the issue (which is intermittent, but frequent)

token-entangler, create entanglement "A seeds constraint was violated."

---

token-metadata/program/src/assertions/collection.rs
token-metadata/program/tests/update_metadata_account_v2.rs
token-metadata/program/tests/verify_collection.rs

Updating `Metadata` accounts with a `verified` collection requires that users "un verify" their collection to properly update. This fix allows for updates, as long as you maintain the verified collection state.

Allow Metadata updates when it contains a Verified Collection

---

candy-machine/program/Cargo.lock
candy-machine/program/Cargo.toml
candy-machine/program/src/lib.rs
candy-machine/program/src/utils.rs

TLDR; CHARGE BOTs .01 SOL (could increase)
This is not the end solution but it will be effective in discouraging bots.
Candymachine has one of the lowest success rates for programs on solana
A very high number of those transactions are clear cases where a bot is doing something bad, trying to mint before the mint is open, minting after the candy machine is empty, minting without a WL token 
Example: 
This is an image of a CandyMachineNotLive error.
This PR adds a hard-coded bot tax of 0.01 sol (we may increase this) and it will charge the wallet this amount or all of their funds whatever is higher under the following conditions:
The funds are sent to the Token Metadata program account, this is to avoid any client changes needed to adopt this change. More pervasive changes are needed to …

Its time we did something about bots

---

candy-machine/program/Cargo.toml
candy-machine/program/src/lib.rs

This PR reorders the checks on the WL token burn ix to after the go live date checks. This should prevent WL tokens from being burned if a txn "fails" from the bot punish function.

Fix: prevent WL token burn before punish bot calls

---

auction-house/program/Cargo.toml

`mpl-testing-utils` v0.0.2 relies on an older version of `token-metadata` so blocks us from publish auction house as a crate. However, it's a dev dependency so isn't actually required for the functional crate stuff. Removing the crate dependency and leaving it as a path means it gets ignored by Cargo when it's published.

refactor(auction-house): remove mpl-testing-utils crate dep

---

.github/actions/anchor-build/action.yaml
.github/actions/build-and-publish/action.yaml
.github/actions/install-anchor/action.yml
.github/actions/upload-to-s3/action.yaml

* We want to store binaries related for programs at specific points in time. These changes will allow us to add workflows that build a program via anchor and upload that output + metadata to AWS S3.
* When including the `build-and-upload` action, 
* we will save the output of `anchor build --verifiable` to bucket at `<bucket-name>/program-name/commit-sha/program-name.so`.
* we will save a file called `index.json` with some basic metadata at `<bucket-name>/program-name/index.json`. Right now, this will contain the commit URL, ID, timestamp, and a URL to the most recent binary uploaded to the bucket for that program.
* These changes use the [OpenID Connect model](https://github.blog/changelog/2021-10-27-github-actions-secure-cloud-deployments-with-openid-connect) to connect GH with AWS, as …

build: add verfiable builds via anchor and uploads to S3

---

metaplex/js/src/accounts/BidRedemptionTicket.ts

This code is copied from https://github.com/metaplex-foundation/metaplex/blob/master/js/packages/common/src/models/metaplex/index.ts#L663
First of all, thanks for the awesome work you all are doing!
In building a UI, to handle NFT auctions, we had a really hard time trying to figure out how to determine if a participation bid had been redeemed.  Ultimately, we found this code snippet and thought, given the core use case it solves, that it would make sense to have it here.

Adds a hasBeenRedeemed() method

---

.github/workflows/program-fixed-price-sale.yml
Cargo.lock
fixed-price-sale/js/package.json
fixed-price-sale/js/test/transactions/buy.ts
fixed-price-sale/program/Cargo.toml
fixed-price-sale/program/src/processor/save_primary_metadata_creators.rs
fixed-price-sale/program/src/processor/withdraw.rs
fixed-price-sale/program/src/state.rs

The imported creators type from token metadata has no anchor serialize, or account trait impl and this stops it from getting proper treatment from the idl generator.
create a new type that gets saved in the runtime that can be properly idl'ed

switches types so idel gen happens with no issue

---

.github/actions/fetch-pr-labels/action.yaml
.github/actions/map-labels-to-version/action.yaml
.github/actions/map-pr-review-to-version/action.yaml
.github/actions/map-pr-review-to-version/script.js
.github/actions/publish-to-crates/action.yaml
.github/actions/publish-to-npm/action.yaml
.github/actions/update-cargo-version/action.yaml
.github/actions/update-cargo-version/script.js

These are additional Github actions to assist on the quest for auto-publishing. These are likely not the final end-state but rather something to get us started and get a better feel for the workflow they enable.
On PR merge, these actions can be triggered to do the following:
1. Fetch expected semvar version from PR. There are two possibilities here:
- grab a PR's reviews from PR in reverse chronological order and look for a matching `patch|minor|major` comment.
- grab a PR's labels and search for a specific label indicating a version bump
2. Modify package version based on the output from step 1. If no command was found, exit job. 
3. Commit and tag changes via git
4. Publish to respective registry — NPM for JS, Crates for Rust.
3. Push changes to Github
* These actions unused right now. …

Add auto-publishing to NPM and crate registry based on PR comment

---

candy-machine/program/tests/core/helpers.rs
candy-machine/program/tests/utils/candy_manager.rs

The spec for mint NFT success of CM was assigning ownership of the NFT to the nft_info.token instead of the payer for the mint.
- Add assertion to mint_nft test for the owner of the NFT being the payer.
- Fix prepare_nft helper method to assign ownership to the minter.
```
[2022-05-31T16:21:31.605867000Z DEBUG solana_rbpf::vm] BPF instructions executed (interp): 22881
[2022-05-31T16:21:31.605876000Z DEBUG solana_rbpf::vm] Max frame depth reached: 13
[2022-05-31T16:21:31.605883000Z DEBUG solana_runtime::message_processor::stable_log] Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ consumed 51385 of 1231572 compute units
[2022-05-31T16:21:31.605937000Z DEBUG solana_runtime::message_processor::stable_log] Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ success
thread 'main' panicked …
```

[CM] [Specs] Assert Minter is the Owner of the NFT 

---

.github/actions/get-pr-for-commit/action.yaml
.github/actions/publish-to-crates/action.yaml
.github/actions/publish-to-npm/action.yaml
.github/actions/setup-aws-env/action.yaml
.github/workflows/program-auction-house.yml
.github/workflows/program-auction.yml
.github/workflows/program-candy-machine.yml
.github/workflows/program-fixed-price-sale.yml
.github/workflows/program-gumdrop.yml
.github/workflows/program-metaplex.yml
.github/workflows/program-nft-packs.yml
.github/workflows/program-token-entangler.yml
.github/workflows/program-token-metadata.yml
.github/workflows/program-token-vault.yml
.github/workflows/sdk-auction-house.yml
.github/workflows/sdk-auction.yml
.github/workflows/sdk-candy-machine.yml
.github/workflows/sdk-core.yml
.github/workflows/sdk-fixed-price-sale.yml
.github/workflows/sdk-gumdrop.yml
.github/workflows/sdk-metaplex.yml
.github/workflows/sdk-token-entangler.yml
.github/workflows/sdk-token-metadata.yml
.github/workflows/sdk-token-vault.yml

* This change wires up the actions I previously added for verifiable builds and NPM & Crates versioning
* https://github.com/metaplex-foundation/metaplex-program-library/pull/488
* https://github.com/metaplex-foundation/metaplex-program-library/pull/515
* When a PR is merged, it triggers a `push` event to master. In this case, the workflow checks for (1) changes in the package and (2) a `push` event before trying to publish a new version and build, in the case of Rust
* Most changes are adding the top-level actions for publishing version updates for JS (`publish-to-npm`) & Rust (`publish-to-cratess`) and publishing builds for Rust (`build-and-publish`)
* During a push event, we don't have access to the associated PR number. So, I added a custom `get-pr-for-commit` action that takes the …

Add versioning and build actions to workflows

---

token-metadata/js/idl/mpl_token_metadata.json
token-metadata/js/src/generated/errors/index.ts
token-metadata/js/src/generated/instructions/BurnNft.ts
token-metadata/program/src/error.rs
token-metadata/program/src/instruction.rs
token-metadata/program/src/processor.rs
token-metadata/program/tests/burn_nft.rs

v1.3.1
Prevents print editions and master editions with a supply > 0 from being burned in `burn_nft` until we decide how to handle burning print editions. (If it's decided to do this it should be in a new handler e.g. `burn_print_nft`). 
Adds two new errors.
Fixes a bug where collection items belonging to unsized collections couldn't be burned.
This changes the TypeScript package slightly by adding two new errors to the IDL and changing some account names and descriptions. 
Some comments and explanations on the changes:
This verbosity 
```rust
// Ensure this is a Master Edition and not a Print.
// Scope this so the borrow gets dropped and doesn't conflict with the mut borrow
// later in the handler when overwriting data.
{
let edition_account_data = edition_info.try_borrow_data()?;
// …
```

Fix burning editions

---

token-metadata/Cargo.toml
token-metadata/js/idl/mpl_token_metadata.json
token-metadata/js/src/generated/instructions/SetCollectionSize.ts
token-metadata/program/Cargo.toml
token-metadata/program/src/instruction.rs
token-metadata/program/src/processor.rs
token-metadata/program/src/utils.rs
token-metadata/program/tests/set_collection_size.rs

A few more changes to be included in v1.3.1:
* ~~Set Collection Size allows setting size for both Some and None variants of the collection_details field~~.
* Add overflow checks to release profile in Cargo.toml
* Add optional account to Shank annotations for Set Collection SIze
* Perform checked addition and subtraction for collection size math
* Regenerate the JS SDK
Pivot:
There are attacks possible with allowing `set-collection-size` to always update the size. Instead, it's going to only allow unsized collection Parents to be set (If the collection details is not populated or set to `None`).  This means a collection size can only be set once, after that a new collection has to be created and the items migrated over. This is annoying for users who mess up but makes it so the on-chain …

refactor(token-metadata): set-collection-size

---

.github/actions/install-anchor/action.yml
.github/actions/install-solana/action.yml
.github/actions/list-changed-files/action.yaml
.github/actions/list-changed-files/script.js
.github/actions/make-version-changes/action.yaml
.github/actions/make-version-changes/script.js
.github/actions/parse-version-command/action.yaml
.github/actions/parse-version-command/script.js
.github/workflows/pr-comment.yml
release.toml

Address auto-versioning and publishing outlined in #123 and #124. 
* The first approach in #515 and #540 failed because `master` is write-protected. Thus, we couldn't update and push changes **after** a PR was merged.
* If merged, this is part 1️⃣ of 2️⃣.
* Part 1️⃣: track version comments (`version patch|minor|major`), perform the version bump and append the commit to the PR. Note: this is done by pushing the commit to the same branch as the PR. 
* Part 2️⃣: track when a PR was actually merged, and process any package publishing if needed.
* Version command that triggers the workflow right now is = `version patch|minor|major`. But, the workflow is setup to handle more detailed commands in the future - e.g. `version patch:rust minor:auction-house:js` or something like that.
* Someone …

build: append version to pr flow

---

.github/workflows/program-auction-house.yml
.github/workflows/program-auction.yml
.github/workflows/program-candy-machine.yml
.github/workflows/program-fixed-price-sale.yml
.github/workflows/program-gumdrop.yml
.github/workflows/program-metaplex.yml
.github/workflows/program-nft-packs.yml
.github/workflows/program-token-entangler.yml
.github/workflows/program-token-metadata.yml
.github/workflows/program-token-vault.yml
.github/workflows/sdk-auction-house.yml
.github/workflows/sdk-auction.yml
.github/workflows/sdk-candy-machine.yml
.github/workflows/sdk-core.yml
.github/workflows/sdk-fixed-price-sale.yml
.github/workflows/sdk-gumdrop.yml
.github/workflows/sdk-metaplex.yml
.github/workflows/sdk-token-entangler.yml
.github/workflows/sdk-token-metadata.yml
.github/workflows/sdk-token-vault.yml

I recently discovered that `master` is push protected and that a GH action cannot (force) push a change - sources below. 
Thus, all workflows I added in PR #540 will not work since they try to push to master. This change removes the versioning actions from those workflows to prevent further failed workflows while I figure out a new approach.
I only removed lines that I previously added in #540, which are related to permissions and version/build actions.
Sources: 
https://github.community/t/how-to-push-to-protected-branches-in-a-github-action/16101
https://github.community/t/allowing-github-actions-bot-to-push-to-protected-branch/16536

Remove versioning actions from rust and sdk workflows

---

.github/workflows/pr-comment.yml

This change will dump event context to the console on every invocation. This is useful in debugging.

build: dump event context on event invocation

---

.github/actions/publish-version-changes/action.yaml
.github/actions/publish-version-changes/script.js
.github/workflows/manually-sync-package-versions.yml

* We will eventually use actions + workflows to help automate package publishing - supplementing the logic added here #558 
* It turns out we can re-purpose some shared code, with a manual package publishing workflow. Anyone can directly invoke this workflow from the GH UI, specifying the packages they want to sync, e.g. `["candy-machine/js"]`.
* The workflow will go through each element in the list, check the local vs remote package versions. If they don't match, we will try to publish with the updated package with the respective package manager.
Example workflow of the run on my forked repo, with input = `["candy-machine/js", "token-metadata/program"]`: https://github.com/jshiohaha/metaplex-program-library/runs/7106341908?check_suite_focus=true

build: add workflow for manually syncing package versions

---

.github/actions/make-version-changes/script.js

This [version build](https://github.com/metaplex-foundation/metaplex-program-library/runs/7114734718?check_suite_focus=true) failed because the expected didn't match the actual IDL. `fixed_price-sale.json` should have been `fixed_price_sale.json` - in this case, we'll use `replace` in favor of `replaceAll`.
```
Error: Unhandled error: Error: Command failed: cp /home/runner/work/metaplex-program-library/metaplex-program-library/target/idl/fixed_price-sale.json /home/runner/work/metaplex-program-library/metaplex-program-library/fixed-price-sale/js/idl
```
I ran `anchor build --skip-lint --idl ../../target/idl` from `<path-to-mpl>/metaplex-program-library/fixed-price-sale/program` and the command generated an IDL named `fixed_price_sale.json`

build: use replaceAll instead of replace

---

.github/actions/make-version-changes/script.js

RIP - apparently `replaceAll` is only implemented as of **Node v14.15.0** ([source](https://stackoverflow.com/questions/65295584/jest-typeerror-replaceall-is-not-a-function)). So, the solution is to revert **back** to `replace` with a regex global modifier instead of a string.
I created a temporary PR to reproduce the error & test: https://github.com/metaplex-foundation/metaplex-program-library/pull/572
Build with error ❌ https://github.com/metaplex-foundation/metaplex-program-library/runs/7118169485?check_suite_focus=true
Build with success ✅ https://github.com/metaplex-foundation/metaplex-program-library/runs/7118550342?check_suite_focus=true

build: use replace with a global modifier

---

.github/actions/list-changed-files/action.yaml
.github/actions/list-changed-files/script.js
.github/actions/publish-version-changes/script.js
.github/workflows/pr-comment.yml
.github/workflows/publish-on-pr-merge.yml

* version changes (original change in #558) are requested & added to PRs while they are open.
* after merge, this workflow will trigger and try to sync the updated version on master with the package manager.
* simultaneously, we add and push tags based on the upgraded package(s).
* test pr: https://github.com/jshiohaha/metaplex-program-library/pull/25
* version flow: https://github.com/jshiohaha/metaplex-program-library/runs/7143773815?check_suite_focus=true
* publish & tag: https://github.com/jshiohaha/metaplex-program-library/runs/7143997677?check_suite_focus=true
* note: this test didn't actually publish the packages to npm/crates + tag the repo because i used dummy tokens

build: publish version changes on PR merge

---

.github/workflows/verify-api-on-pr-open.yml

if accepted, this workflow will run `yarn api:gen` against the modified package(s) when someone (re)opens or synchronizes a PR against `master` with any rust changes. 
* a passing build means the API is in a good state
* a failing build means the contributor needs to run `yarn api:gen`
**note**: we use solita to automatically generate the SDK. solita installs anchor based on the version specified in the local `Cargo.toml`, which isn't cached. so, the workflow runtime can get quite long.
* `candy-machine` needs update: https://github.com/jshiohaha/metaplex-program-library/runs/7125090320?check_suite_focus=true
* `candy-machine` & `auction-house` is OK: https://github.com/jshiohaha/metaplex-program-library/runs/7125944578?check_suite_focus=true

build: verify sdk is up-to-date for rust changes

---

.github/actions/publish-version-changes/script.js

update tag name format for rust crates. see prev tags here https://github.com/metaplex-foundation/metaplex-program-library/tags

build: modify name for crate tag on publish

---

.github/workflows/verify-lib-on-pr-open.yml

* Use local package's version of `solita` instead of installing the latest version
* Explicitly look for rust files in change, to avoid any false-positives for top-level packages (e.g. [here](https://github.com/metaplex-foundation/metaplex-program-library/runs/7219069783?check_suite_focus=true))
* Replace api/sdk naming with library, following a slack discussion

build: reference local version of solita during install

---

token-metadata/program/Cargo.toml
token-vault/program/Cargo.toml

`anchor-spl` depends on both `metaplex-token-metadata` and `spl-token`, and `metaplex-token-metadata` depends on `spl-token`, but both have specified dependencies with a `~`, meaning that only patch version bumps are allowed by the Cargo resolver, and not minor version bumps.
The Solana CI used to build Anchor and Metaplex to check for downstream breakage, but because of Anchor's metaplex dependency, it's impossible to select a viable package of `spl-token` when building Anchor, since the Solana crates use version `3.3`, but metaplex-token-metadata only allows `3.2`.
Currently, Anchor can't upgrade because of its dependency on token-metadata.
Since `metaplex-token-metadata` is used by many other programs, it will be much more usable to relax the version requirements to the default on the …

token-metadata: Remove tilde in dependencies to fix future package resolving

---

token-metadata/program/src/state.rs

The PR I merged yesterday adding `serde` as an optional feature to `token-metadata` was missing the serde feature on a few structs. I added it to them so all our structs in that program have it and then added some disambiguations for struct methods calling `serialize` since both `serde`'s `Serialize` trait and `BorshSerialize` have a `serialize` method.

fix: add serde feature to rest of structs; disambiguate serialize calls

---

.github/actions/publish-version-changes/action.yaml

Running `yarn init --yes` will overwrite the existing `package.json` with information about workplace packages. We can see this in a problematic workflows related to @samuelvanderwaal PR (#579):
1. `Sync versions on PR merge `: https://github.com/metaplex-foundation/metaplex-program-library/runs/7259707927?check_suite_focus=true
```
Usage Error: The nearest package directory (/home/runner/work/metaplex-program-library/metaplex-program-library/token-metadata/js) doesn't seem to be part of the project declared in /home/runner/work/metaplex-program-library/metaplex-program-library.
- If the project directory is right, it might be that you forgot to list token-metadata/js as a workspace.
- If it isn't, it's likely because you have a yarn.lock or package.json file there, confusing the project …
```

build: use existing yarn workspace inside publish version workflow

---

.github/workflows/manually-sync-package-versions.yml

I used the wrong value for the NPM secret stored in GH 🤦🏼‍♂️ double checked here https://github.com/metaplex-foundation/metaplex-program-library/settings/secrets/actions
The [last manual sync workflow run](https://github.com/metaplex-foundation/metaplex-program-library/runs/7261794106?check_suite_focus=true) failed due to missing permissions - we can see the script was invoked with an empty secret: 
```
with:
script: const script = require('.github/actions/publish-version-changes/script.js')
await script(["token-metadata/js"], '***', '')
```
This caused issues with permissions
```
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to https://registry.npmjs.org/
npm ERR! need auth You need to authorize this machine using `npm adduser`
npm ERR! A complete …
```

build: update NPM secret name

---

auctioneer/program/Cargo.lock
auctioneer/program/src/execute_sale/mod.rs

There is a bug in the Auctioneer (timed auction) `execute_sale` method, where no `remaining_accounts` are passed forward in the CPI  to AuctionHouse – but AuctionHouse expects `remaining_accounts` to be passed to pay creators.
Specifically: The `execute_sale` function CPI's into the` auctioneer_execute_sale` function in AuctionHouse. This in turn calls the `auctioneer_execute_sale_logic` function which calls the `pay_creator_fees` function. Here,`ctx.remaining_accounts` is passed in as an argument. However, `ctx.remaining_accounts` will always be empty, since the CPI from `execute_sale` (the initial call) never forwards any `remaining_accounts`
This results in an error: `insufficient account keys for instruction`
The fix is to "forward" `remaining_accounts` passed by the initial caller …

fix(auctioneer): pass remaining accounts in sale execution

---

.github/workflows/verify-lib-on-pr-open.yml

Recent runs of `verify-lib-on-pr-open` have been failing ([link](https://github.com/metaplex-foundation/metaplex-program-library/actions/workflows/verify-lib-on-pr-open.yml)) due to yarn updating yarn.lock on `yarn` command.
The only way I know how to fix this is adding `YARN_ENABLE_IMMUTABLE_INSTALLS=false` and then ignoring any yarn.lock changes.
Tested run here in my local fork: https://github.com/jshiohaha/metaplex-program-library/runs/7325387492?check_suite_focus=true

build: disable immutable installs in verify package workflow

---

.github/workflows/verify-lib-on-pr-open.yml

Thanks to @samuelvanderwaal for pointing out this issue - some packages do not have `js` dirs or do not have `api:gen` scripts in their local package.json. In this case, we want to avoid running this workflow.
In the case that there are no packages to check, we also want to avoid installing the linux, rust, solana dependencies.
* auction
* metaplex
* core
* nft-packs
* auction-house
* auctioneer
* candy-machine
* fixed-price-sale
* gumdrop
* token-entangler
* token-metadata
* token-vault
* Workflow that quit early with no changes to verify: https://github.com/jshiohaha/metaplex-program-library/runs/7398709423?check_suite_focus=true
* Workflow that found a change to verify (I cancelled the workflow after): https://github.com/jshiohaha/metaplex-program-library/actions/runs/2693730972

build: filter packages on verify lib workflow

---

token-metadata/program/Cargo.toml

I missed this last dependency conflict on my other changes. [spl-associated-token-account 1.0.5](https://crates.io/crates/spl-associated-token-account/1.0.5/dependencies) depends on spl-token ^3.3.0 which causes conflicts when clients try to use the Rust package with other Solana dependencies which are pinned to spl-token 3.2. We need to stay on 3.2 until we bump everything to the 1.10 series.

fix: drop spl-associated-token-account to 1.0.3

---

.github/actions/make-version-changes/action.yaml
.github/actions/make-version-changes/script.js
.github/workflows/pr-comment.yml

Whenever someone comments `version patch|minor|major` on a PR, the `Version updates` workflow kicks off to make a version update. As of now, that version update is just **pushed** to the source branch - this works fine for PRs coming from the same repo.
* **Problem**:  The above flow breaks for PRs coming from forks - example [here](https://github.com/metaplex-foundation/metaplex-program-library/runs/7350428294?check_suite_focus=true). We cannot simply push commits to forks in a workflow - https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token.
* **Proposed solution**: Instead, I'm thinking we can 
1. make the same version changes as usual, 
2. open a new PR in the fork repo against the original PR branch
3. comment on the original PR with a request …

build: enable version workflow for changes in forks

---

.github/workflows/program-auction-house.yml
.github/workflows/program-auctioneer.yml

The testnet cluster uses 1.11 which requires cargo-test-sbf which doesn't seem to work with the installed Solana runtime. I'm punting and removing it from the test matrix.

Removing testnet tests

---

token-metadata/program/src/instruction.rs

Slight issue with the Shank macro of the `RevokeCollectionAuthority` instruction which bubbles up to the generated libraries used by the SDK.
We do not need the `delegate_authority` as a signer since the `revoke_authority` already plays that role.
See account meta below.
https://github.com/metaplex-foundation/metaplex-program-library/blob/4ff5133d416795234103486f76291e9e72dc40de/token-metadata/program/src/instruction.rs#L1254

fix: revoking collection authority only needs one signer

---

.github/workflows/verify-lib-on-pr-open.yml

Modify `Verify package library` workflow such that it doesn't fail (and block) a PR from being merged - instead, the workflow will simply append an informational comment to the PR if it detects any JS lib changes via `yarn api:gen`. Subsequent actions are left up to the contributor and reviewers.
Sample comment on [this test PR](https://github.com/jshiohaha/metaplex-program-library/pull/116) in my MPL fork:
> Workflow `Verify package library` found differences when running `yarn api:gen` in the JS lib for `candy-machine`. Please see the job for more details: https://github.com/jshiohaha/metaplex-program-library/actions/runs/2792414594.

feat: add comment to pr on verify lib workflow failure

---

.github/actions/parse-version-command/script.js
.github/workflows/pr-comment.yml

GH doesn't provide out-of-the-box support for multi-line content bodies, so here we will replace actual returns & newlines with `\n\r` characters. Now, the workflow should work with comments like this
```
This is a
multi-line
comment. Please don't break
the CI
```
```
This looks good to me, 
my only question is a logic one should we allow them to set FungibleAsset if the mint has a higher than one max supply. I dont think that answer should be scoped to this PR
```
* https://github.com/jshiohaha/metaplex-program-library/pull/127
* Job 1 with **Sample input 1**: https://github.com/jshiohaha/metaplex-program-library/actions/runs/2802194714
* Job 2 with **Sample input 2**: https://github.com/jshiohaha/metaplex-program-library/actions/runs/2802193373

build: process PR review content body

---

token-metadata/program/src/deprecated_processor.rs
token-metadata/program/src/processor.rs
token-metadata/program/src/state.rs
token-metadata/program/src/utils.rs
token-metadata/program/tests/create_metadata_account.rs
token-metadata/program/tests/update_metadata_account_v2.rs

- Remove requirement that one of the creators is the update authority
when metadata account is being created.
- Flatten some of the logic and use positive conditionals that
should be easier to understand.
- Use hashmaps instead of nested loops/iterators to look for duplicates
in one Vec or common addresses between multiple Vecs.
- Add new check for existing verified creators in assert_data_valid.
- Adding tests for:
- allow update authority to not be creator.
- cannot unverify another creator by changing the verified flag.
- cannot unverify another creator by removing them from the array.

Refactor `assert_data_valid` in `token-metadata`

---

README.md
auction/js/package.json
bubblegum/js/package.json
candy-machine/js/package.json
core/js/package.json
gumdrop/js/package.json
metaplex/js/package.json
token-entangler/js/package.json
token-vault/js/package.json

Update all instances of `prepublish` to `prepublishOnly` because prepublish is deprecated - https://docs.npmjs.com/cli/v8/using-npm/scripts
The publish CI flow published [@metaplex-foundation/mpl-candy-machine](https://www.npmjs.com/package/@metaplex-foundation/mpl-candy-machine) version [4.4.0](https://unpkg.com/browse/@metaplex-foundation/mpl-candy-machine@4.4.0) be published without a `dist/` folder, creating problems for consumers. The expected layout can be seen in [v4.3.0](https://unpkg.com/browse/@metaplex-foundation/mpl-candy-machine@4.3.0).
We are thinking this happened because the publish flow did **not** validate the package was buildable before publishing. The JS packages rely on pre/post scripts to help with this sort of functionality, and some packages were using the now …

fix: change all instances of prepublish to prepublishOnly

---

auction-house/program/Cargo.toml

This commit adds `overflow-checks=true` to the release profile of the Auction House contract as a security precaution against unexpected behaviour regarding unchecked arithmetic operations in the program in a release build.
The recommendation comes from an audit by Halborn.

Add overflow-checks to the release profile

---

.github/workflows/verify-lib-on-pr-open.yml

When running `Verify package library` workflow, we were running `api:gen` against master when we should have been running against the PR head ref. This change makes sure we checkout the code on the same branch as the PR when performing the lib diff.
I tested in my personal fork
* PR: https://github.com/jshiohaha/metaplex-program-library/pull/136
* Workflow **before** `api:gen` ended with a diff & PR message: https://github.com/jshiohaha/metaplex-program-library/runs/8005248662?check_suite_focus=true
* Workflow **after** `api:gen` ended with no diff & no message: https://github.com/jshiohaha/metaplex-program-library/runs/8005374148?check_suite_focus=true

build: run api:gen against head ref instead of master

---

token-metadata/program/src/deprecated_processor.rs
token-metadata/program/src/processor.rs
token-metadata/program/src/utils.rs

- Make sure that `mint_authority` is owned by Bubblegum program and
is a signer before allowing creator to be verified without all
checks in place.
- Feature currently hardcoded to inactive.
- Needed to support Bubblegum `decompress` instruction.
- Also simplifity `allow_direct_creator_writes` parameter to be only
at a lower level where it will be used.

Allow Bubblegum program to create metadata with verified creators

---

bubblegum/program/download-compression-programs.sh

-Downloads and builds account-compression program (formerly known
as gummyroll).
-Downloads and builds wrapper program (formerly known as candy-
wrapper).
-Script inspired by/based on:
https://github.com/metaplex-foundation/digital-asset-rpc-infrastructure/blob/main/download-programs.sh

Adding script to download SPL programs used for Bubblegum testing

---

bubblegum/js/idl/bubblegum.json
bubblegum/js/src/generated/accounts/Voucher.ts
bubblegum/js/src/generated/errors/index.ts
bubblegum/js/src/generated/instructions/approveMintAuthorityRequest.ts
bubblegum/js/src/generated/instructions/burn.ts
bubblegum/js/src/generated/instructions/cancelRedeem.ts
bubblegum/js/src/generated/instructions/closeMintRequest.ts
bubblegum/js/src/generated/instructions/compress.ts
bubblegum/js/src/generated/instructions/createDefaultMintRequest.ts
bubblegum/js/src/generated/instructions/createTree.ts
bubblegum/js/src/generated/instructions/delegate.ts
bubblegum/js/src/generated/instructions/mintV1.ts
bubblegum/js/src/generated/instructions/redeem.ts
bubblegum/js/src/generated/instructions/requestMintAuthority.ts
bubblegum/js/src/generated/instructions/setAndVerifyCollection.ts
bubblegum/js/src/generated/instructions/setTreeDelegate.ts
bubblegum/js/src/generated/instructions/transfer.ts
bubblegum/js/src/generated/instructions/unverifyCollection.ts
bubblegum/js/src/generated/instructions/unverifyCreator.ts
bubblegum/js/src/generated/instructions/verifyCollection.ts
bubblegum/js/src/generated/instructions/verifyCreator.ts
bubblegum/js/src/generated/types/InstructionName.ts
bubblegum/program/Cargo.toml
bubblegum/program/src/error.rs
bubblegum/program/src/lib.rs
bubblegum/program/src/state/metaplex_adapter.rs
bubblegum/program/src/utils.rs

- Also:
- Adding new error variants.
- Cargo fmt and clippy fixes.
- Removing a collection TODO since we solved
a different way.
- Adding `#[allow(unreachable_patterns)]` on one specific unsupported
schema error.
- Updating token-metadata to be a crates.io version.
- Regenerating API.

Replacing asserts with explicit errors + more

---

.github/workflows/program-auction-house.yml
.github/workflows/program-auction.yml
.github/workflows/program-auctioneer.yml
.github/workflows/program-candy-machine.yml
.github/workflows/program-fixed-price-sale.yml
.github/workflows/program-gumdrop.yml
.github/workflows/program-metaplex.yml
.github/workflows/program-nft-packs.yml
.github/workflows/program-token-entangler.yml
.github/workflows/program-token-metadata.yml
.github/workflows/program-token-vault.yml
.github/workflows/sdk-auction-house.yml
.github/workflows/sdk-auction.yml
.github/workflows/sdk-candy-machine.yml
.github/workflows/sdk-core.yml
.github/workflows/sdk-fixed-price-sale.yml
.github/workflows/sdk-gumdrop.yml
.github/workflows/sdk-metaplex.yml
.github/workflows/sdk-nft-packs.yml
.github/workflows/sdk-token-entangler.yml
.github/workflows/sdk-token-metadata.yml
.github/workflows/sdk-token-vault.yml

Update paths filters to only include rust subdirs for program workflows and js subdirs for sdk workflows. This should prevent program tests from running when only js changes are made, and vice versa.

build: update path filters to include program/js subdirs

---

auction-house/program/Cargo.lock
auction-house/program/Cargo.toml
auction-house/program/src/utils.rs
auction-house/program/tests/execute_sale.rs
auction-house/program/tests/utils/helpers.rs
auction-house/program/tests/utils/setup_functions.rs

Some Auction House execute sale tests are encountering time issues in CI resulting in IOErrors.
This was mitigated by the below
- test: increase compute units to max in hopes to fix tests
- ci: fix test flakiness by allowing IoErrors in CI for known cases
Auction House was still using the now obsolete token metadata dependency to access the
`Metadata` type. 
This was fixed by making it use `mpl-token-metadata` instead.

chore: stabilize auction-house tests in CI

---

bubblegum/program/src/lib.rs

- @austbot originally found this in a previous PR but I didn't understand his comment.
- Then @alexandruag found when running `verify_creator` in a test.

Fix creator hash

---

.github/workflows/pr-comment.yml

Small update in workflow after a vulnerability from code scanning https://github.com/metaplex-foundation/metaplex-program-library/security/code-scanning/1
* Tested in my personal fork
* single line comment, no version: https://github.com/jshiohaha/metaplex-program-library/actions/runs/3053361588
* multi-line comment, no version: https://github.com/jshiohaha/metaplex-program-library/actions/runs/3053374366
* multi-line comment with version: https://github.com/jshiohaha/metaplex-program-library/actions/runs/3053376846

build: use shell syntax for user input to prevent injection attack

---

token-metadata/program/src/escrow/create_constraint_model.rs
token-metadata/program/src/escrow/mod.rs
token-metadata/program/src/escrow/state.rs
token-metadata/program/src/instruction.rs
token-metadata/program/src/processor.rs
token-metadata/program/src/state_test.rs

This PR makes `EscrowConstraintType::Tokens` hold `HashMap<Pubkey, bool>`. I snuck in a rename from `escrow_constraints_model` to `escrow_constraint_model` and adjusted one of the shank attributes on `CreateEscrowAccount`.

Change Structure of `EscrowConstraintType::Tokens`

---

.github/actions/install-anchor/action.yml
.github/actions/install-common-build-deps/action.yml
.github/actions/install-shank/action.yml

* We now have a cache-able action to install `shank-cli` like linux deps, rust, and solana, anchor, etc.
* We now also have a wrapper around all common program build dependencies. We can now install with something as simple as (1) instead of (2). However, we still have flexibility to exclude certain dependencies we don't want. In the future, we can also extend to specify versions, or fallback to a default.
**(1) possibly new way of installing dependencies**
```
- uses: ./.github/actions/install-common-build-deps
```
**(2) old way of installing dependencies**
```
- uses: ./.github/actions/install-linux-build-deps
- uses: ./.github/actions/install-rust
with:
toolchain: ${{ env.RUST_TOOLCHAIN }}
- uses: ./.github/actions/install-solana
- uses: ./.github/actions/install-anchor 
```

Add shank install and wrapper action for program dependencies

---

bubblegum/program/Cargo.toml

This change supports blockbuster, by downgrading spl associated token account to be more compatible with anchor

Downgrades SPL ASSOC

---

auction-house/js/README.md

ReadMe inside auction-house/js had a typo.
it should've been 
```yarn api:gen``` 
instead of 
```yarn gen:api```
Fixed that.

fix: yarn command

---

bubblegum/program/Cargo.lock
bubblegum/program/Cargo.toml
bubblegum/program/src/lib.rs
bubblegum/program/src/state/metaplex_anchor.rs
bubblegum/program/src/state/mod.rs
bubblegum/program/src/utils.rs

Removes hard an unnecessary dep on anchor spl, this PR unblockes some block buster testing work

Dependency Cleanup to use MB version of solana

---

core/rust/testing-utils/Cargo.lock
core/rust/testing-utils/Cargo.toml
core/rust/testing-utils/src/solana.rs

There's a breaking change between spl-associated-token-account 1.0.5 and 1.1.0. The newer version requires an extra parameter passed into the `instruction::create_associated_token_account` so we need to pin to 1.0.5 so Cargo doesn't try to grab the newer version.

fix(testing-utils): pin to spl-associated-token-account 1.0.5

---

token-metadata/Cargo.lock
token-metadata/js/idl/mpl_token_metadata.json
token-metadata/program/Cargo.toml

This may not be strictly necessary since I removed the tilde pinning allowing more flexibility with versions.

chore: bump token-metadata deps

---

bubblegum/js/README.md
bubblegum/js/package.json

Current link works when you have the repo but doesn't work on npm

Fix readme link to use full path

---

LICENSE
auction-house/program/Cargo.toml
auctioneer/program/Cargo.toml
bubblegum/program/Cargo.toml
candy-machine-core/program/Cargo.toml
candy-machine/program/Cargo.toml
core/rust/testing-utils/Cargo.toml
fixed-price-sale/program/Cargo.toml
gumdrop/program/Cargo.toml
hydra/program/Cargo.toml
nft-packs/program/Cargo.toml
token-entangler/program/Cargo.toml
token-metadata/program/Cargo.toml

As the publisher of the non-fungible token (NFT) standard for the Solana blockchain, we believe in the set of principles that have guided open source software development models over the years – Transparency, Collaboration, Release Early and Often, Community, and Inclusive Meritocracy. 
We have received much community feedback on AGPLv3  being challenging to work with from an upstream Rust package dependency perspective, thus we have adopted an “Apache-style” licensing scheme for our code repositories. To be true to our NFT and crypto legacy, however, we do impose some restrictions on modifying our code that we believe promote the purpose and promise of NFTs in order to protect the web3 ecosystem.

Upgrade to Apache-style license

---

auctioneer/program/Cargo.toml
bubblegum/program/Cargo.toml
candy-machine-core/program/Cargo.toml
candy-machine/program/Cargo.toml
core/rust/testing-utils/Cargo.toml
fixed-price-sale/program/Cargo.toml
gumdrop/program/Cargo.toml
hydra/program/Cargo.toml
nft-packs/program/Cargo.toml
token-entangler/program/Cargo.toml
token-metadata/Cargo.toml
token-metadata/cli/Cargo.toml
token-metadata/program/Cargo.toml

Added to everything even redundant in some cases, even testing utils crate (even though I doubt we would ever need it for that).

Enable integer overflow checks for any crates that were missing it

---

candy-machine/program/tests/core/metadata_manager.rs
candy-machine/program/tests/utils/candy_manager.rs
fixed-price-sale/program/Cargo.lock
fixed-price-sale/program/Cargo.toml
fixed-price-sale/program/tests/utils/helpers.rs
nft-packs/program/tests/claim_card.rs
nft-packs/program/tests/utils/edition_marker.rs
nft-packs/program/tests/utils/metadata.rs
nft-packs/program/tests/utils/pack_set.rs

Updating tests to not pass in `None` for freeze authority to comply with Token Metadata v1.6 changes.

fix: candy machine tests for freeze auth change

---

bubblegum/program/src/lib.rs
bubblegum/program/tests/simple.rs
bubblegum/program/tests/utils/tree.rs

Token Metadata v1.6 disallows setting a freeze authority to `None`. This fixes the DecompressV1 instruction to use the mint authority as the freeze authority. (This is overridden with the edition when create_master_edition is called.)
There are also some `cargo fmt` lints.

fix: set freeze auth in DecompressV1

---

token-metadata/program/src/assertions/collection.rs
token-metadata/program/src/processor.rs
token-metadata/program/src/state.rs
token-metadata/program/src/state_test.rs
token-metadata/program/tests/verify_collection.rs

This PR modifies the `CollectionAuthorityRecord` to add the `update_authority` field:
```
pub struct CollectionAuthorityRecord {
pub key: Key,                         //1
pub bump: u8,                         //1
pub update_authority: Option<Pubkey>, //33 (1 + 32)
}
```
Thanks SolShield for identifying this exploit

Add update authority to collection authority record

---

auction-house/js/idl/auction_house.json
auction-house/js/package.json
auction-house/program/Cargo.lock
auction-house/program/Cargo.toml

This is a bump for Auction House 1.3.4
- 1.3.4 removes a specific ata check that was overly restrictive

Bump version and regen IDL

---

.github/configs/issue-label-automations.yml
.github/workflows/label-automations.yml

This PR aims to facilitate community management by triggering automation upon adding labels on GitHub issues.
It defines the following automation:
- **When the `question` label is added**:
- ✍️ Adds a comment asking the author to open a new post on the Solana Stack Exchange using a link that automatically adds the `metaplex` tag to their post.
- 🚫 Closes the issue.
- **When the `feature request` label is added**:
- ✍️ Adds a comment asking the author to create a new Feature Request on Canny or upvote an existing one. It offers shortcuts to relevant Feature Request boards.
- 🚫 Closes the issue.
- **When the `community contribution` label is added**:
- ✍️ Adds a comment that explicitly states we are looking for community contributions on this issue with some rough guidelines that we can …

Add GitHub label automation

---

auction-house/js/idl/auction_house.json
auction-house/js/src/generated/errors/index.ts
auction-house/program/src/errors.rs
auction-house/program/src/sell/mod.rs

- Creates a new `SaleRequiresExactlyOneSigner` error.
- Throw the new error when both the seller and the authority are passed as signers in the sell instruction.
See #911

[AH] Ensure either the seller or the authority is passed as signer on the sell instruction

---

token-metadata/program/ProgrammableNFTGuide.md

Update Rust examples to use the new instruction builders and include links to the JS examples.

Add instruction builder example and links

---

token-metadata/program/src/error.rs
token-metadata/program/src/processor/mod.rs
token-metadata/program/tests/process_instruction.rs

This PR divides the instruction match in the processor to add a constraint that `ProgrammableNonFungible` assets can only be manipulated by the new instruction handlers.

Split instruction match in processor

---

token-metadata/program/src/assertions/edition.rs
token-metadata/program/src/error.rs
token-metadata/program/src/processor/metadata/create.rs

Add a check on the length of the edition account before indexing for the programmable byte test.

Add length check on edition byte test

---

token-metadata/macro/src/lib.rs

Removes cloning of pubkeys and uses `Box` to heap allocate the `Handler`Builder and `Handler` structs to save on stack space.

box builders and remove clones to save stack space

---

token-metadata/js/test/delegate.test.ts
token-metadata/js/test/lock.test.ts
token-metadata/js/test/revoke.test.ts
token-metadata/js/test/setup/txs-init.ts
token-metadata/js/test/transfer.test.ts
token-metadata/js/test/unlock.test.ts
token-metadata/js/test/update.test.ts
token-metadata/js/test/utils/programmable.ts
token-metadata/program/src/pda.rs
token-metadata/program/src/processor/delegate/delegate.rs
token-metadata/program/src/processor/delegate/revoke.rs
token-metadata/program/src/processor/metadata/mint.rs
token-metadata/program/src/processor/metadata/transfer.rs
token-metadata/program/src/processor/metadata/update.rs
token-metadata/program/src/processor/state/mod.rs
token-metadata/program/src/state/programmable.rs
token-metadata/program/src/utils/programmable_asset.rs
token-metadata/program/tests/delegate.rs
token-metadata/program/tests/lock.rs
token-metadata/program/tests/mint.rs
token-metadata/program/tests/revoke.rs
token-metadata/program/tests/transfer.rs
token-metadata/program/tests/unlock.rs
token-metadata/program/tests/utils/digital_asset.rs

PR to use the token account address as part of the token record seed, given that there is a 1:1 relationship between token account and token record.

Token address on token record seed

---

token-metadata/program/src/state/asset_data.rs
token-metadata/program/src/state/collection.rs
token-metadata/program/src/state/delegate.rs
token-metadata/program/src/state/edition.rs
token-metadata/program/src/state/metadata.rs
token-metadata/program/src/state/mod.rs
token-metadata/program/src/state/programmable.rs

Allow conditional compilation serde implementations for `Pubkey`s to serialize into and from strings instead of `u8` arrays.
This adds support for most public `Pubkey` and `Option<Pubkey>` types, but not all of them. Escrow, notably, is left out as it has a wrapper around its Pubkey. We can add support for this later as it won't be a breaking change.

add ser/deser implementations for pubkeys

---

token-metadata/macro/src/lib.rs
token-metadata/program/tests/utils/digital_asset.rs

This PR changes the way the macro handles default values for optional accounts. Currently, a default value will be added when the optional account is not set. This creates an undesirable behaviour since optional accounts will be present in the transaction: (1) they will take more space on the transaction; and (2) when used on a CPI call, they will need to be added to the outer instruction.
The solution is to only use the default value for required accounts, when accounts are not set.
For required accounts, the code generated is:
```rust
system_program: self.system_program.unwrap_or(solana_program::system_program::ID)
```
For optional accounts, the code generated is (even when the name of the account matches one of the default ones):
```rust
authorization_rules_program: …
```

No default for optional accounts

---

token-metadata/js/test/setup/index.ts
token-metadata/js/test/setup/lut.ts
token-metadata/js/test/setup/txs-init.ts
token-metadata/js/test/transfer.test.ts

This PR adds a test showing how an address lookup table (LUT) can be used to reduce the transaction size of the transfer instruction. The test adds 8 accounts to the LUT:
1. `owner`
2. `owner token record`
3. `token`
4. `mint`
5. `metadata`
6. `master edition`
7.  `rule set PDA`
8. `SYSVAR_INSTRUCTIONS_PUBKEY`
Bigger transaction size reductions can be achieved if more accounts are added to the LUT.

Add transfer test with lookup table

---

token-metadata/js/idl/mpl_token_metadata.json
token-metadata/js/src/generated/types/AssetData.ts
token-metadata/js/test/create.test.ts
token-metadata/js/test/mint.test.ts
token-metadata/js/test/transfer.test.ts
token-metadata/js/test/update.test.ts
token-metadata/js/test/utils/digital-asset-manager.ts
token-metadata/program/src/state/asset_data.rs
token-metadata/program/src/state/metadata.rs
token-metadata/program/tests/create.rs
token-metadata/program/tests/utils/digital_asset.rs

`AssetData` required the `update_authority` pubkey but it was not used – this PR removes it.

Remove unused update authority

---

token-metadata/program/Cargo.toml

Bump Token Authorization Rules crate to `v1.0`.

Bump auth rules version

---

token-metadata/Cargo.lock
token-metadata/program/Cargo.toml

This reduces the Token Metadata binary size from 690,120 to 666,728 bytes by bumping to a version of `mpl-utils` that does not force inlining of functions. Thanks to @blockiosaurus for the work figuring out how to reduce binary size.

bump mpl-utils version to reduce binary size

---

token-metadata/js/test/delegate.test.ts
token-metadata/js/test/transfer.test.ts
token-metadata/program/src/instruction/delegate.rs
token-metadata/program/src/processor/delegate/delegate.rs
token-metadata/program/src/state/mod.rs
token-metadata/program/src/state/programmable.rs
token-metadata/program/src/utils/programmable_asset.rs
token-metadata/program/tests/delegate.rs
token-metadata/program/tests/revoke.rs
token-metadata/program/tests/transfer.rs
token-metadata/program/tests/update.rs
token-metadata/program/tests/utils/programmable.rs

Currently, the `Delegate` instruction does not validate authorization rules even when dealing with `pNFT` – it only validates that the correct rules set has been passed.
The PR defines a set of operations for each delegate type and validates whether the delegate is authorized to get the specified delegate type.
The different scenarios are defined by the different delegate types:
```rust
pub enum DelegateScenario {
Metadata(MetadataDelegateRole),
Token(TokenDelegateRole),
}
```
The scenario is used to define the operation, which can then have a rule set associated:
```rust
let delegate_sale_operation = Operation::Delegate {
scenario: DelegateScenario::Token(TokenDelegateRole::Sale),
};
```
Below is example of a rule set that validates that the delegate address is in an allow list:
```rust …
```

Add validation of authorization rules on delegate

---

token-metadata/Cargo.lock
token-metadata/js/package.json
token-metadata/program/Cargo.toml
token-metadata/program/tests/delegate.rs
token-metadata/program/tests/utils/programmable.rs

This PR bumps Token Auth Rules to include the non-zero byte PDA account check, which simplifies the rule sets.

Update Token Auth Rules dependency

---

token-metadata/program/src/processor/delegate/delegate.rs
token-metadata/program/src/processor/delegate/revoke.rs

This PR relaxes the token standard check on `Delegate` and `Revoke`.

Relax token standard check

---

auction-house/js/idl/auction_house.json
auction-house/program/Cargo.lock
auction-house/program/Cargo.toml
auction-house/program/src/utils.rs
auctioneer/js/idl/auctioneer.json
auctioneer/program/Cargo.lock
auctioneer/program/Cargo.toml
core/rust/testing-utils/Cargo.lock
core/rust/testing-utils/Cargo.toml
core/rust/testing-utils/src/solana.rs
core/rust/testing-utils/src/utils/master_edition_v2.rs
core/rust/testing-utils/src/utils/metadata.rs
fixed-price-sale/js/idl/fixed_price_sale.json
fixed-price-sale/program/Cargo.lock
fixed-price-sale/program/Cargo.toml
fixed-price-sale/program/src/lib.rs
fixed-price-sale/program/src/processor/withdraw.rs
fixed-price-sale/program/tests/buy.rs
fixed-price-sale/program/tests/utils/helpers.rs

This updates `mpl-testing-utils`, `fixed-price-sale`, `auction-house` and `auctioneer` dependencies to Solana 1.14 and Anchor 0.26. `mpl-testing-utils` will need a new version published to crates and then `auction-house` and `auctioneer` will need to bump their versions to the new one.

MPL Testing Utils, AuctionHouse, Auctioneer: Upgrade Deps

---

token-metadata/program/ProgrammableNFTGuide.md

Fixed typos and modified sentences in some places. Also capitalised "api" at one place to have uniformity throughout the document.

Grammar and typo fixes

---

token-metadata/program/src/processor/metadata/migrate.rs

The token standard checks are too strict since there are many legacy `NonFungible` assets without a Token Standard set. The validation of the token standard is done in `mpl-migration-validator` [here](https://github.com/metaplex-foundation/mpl-migration-validator/blob/e8dd04252b3a24548c80f6e285209a62d95c43d4/program/src/processor/migrate/validate.rs#L146), so can be removed from this handler.

remove redundant token standard check

---

hydra/program/src/state.rs
hydra/program/src/utils/logic/distribution.rs

Purpose: Enable the ability to use Hydra fanout account address for creator royalties across SOL and SPL markets.
Background:
When we create a fanout wallet, it'll allow to distribute SOL and SPL funds to the members with the shares setup. But, the tests I've made, and then looking at the code, doesn't offer a uniform address to use so whether the wallet is receiving SOL or SPL tokens, we have only one address to send to. SOL is distributed from the Native account, and SPL tokens from the PDA for each mint out of the Fanout account.
My goal was to use the fanout account as the uniform for accepting both SOL and SPL, and then, when trying to distribute SOL, transferring the extra (besides rent) from the fanout account to the native account, to continue with the regular shares distribution. …

[Hydra] move extra SOL in fanout account to native account to distribute

---

token-metadata/program/src/instruction/delegate.rs
token-metadata/program/src/processor/delegate/revoke.rs
token-metadata/program/src/state/programmable.rs
token-metadata/program/tests/revoke.rs
token-metadata/program/tests/utils/digital_asset.rs

This PR adds the ability to revoke a `TokenDelegateRole::Migration` delegate.

Add revoke for migration delegate

---

token-metadata/js/idl/mpl_token_metadata.json
token-metadata/js/src/generated/instructions/Lock.ts
token-metadata/js/src/generated/instructions/Unlock.ts
token-metadata/js/test/lock.test.ts
token-metadata/js/test/setup/txs-init.ts
token-metadata/js/test/unlock.test.ts
token-metadata/program/src/instruction/mod.rs
token-metadata/program/src/processor/state/lock.rs
token-metadata/program/src/processor/state/mod.rs
token-metadata/program/src/processor/state/unlock.rs

The current logic for lock/unlock of fungibles gives the impression that a delegate can be used to freeze/thaw a token account holding fungibles assets. This PR refactors the code to clearly separate the 3 different authorities that can lock/unlock depending on the token standard:
1. `token delegate` for pNFTs
2. `spl-token delegate` for non-fungibles
3. `freeze authority` for fungibles

Refactor lock and unlock logic

---

token-metadata/js/idl/mpl_token_metadata.json
token-metadata/js/src/generated/types/RevokeArgs.ts

This PR adds the missing `MigrationV1` value to the `RevokeArgs` enum on the JS autogenerated code.

Add migration to revoke args

---

token-metadata/program/src/processor/burn/burn.rs
token-metadata/program/src/processor/burn/nonfungible.rs
token-metadata/program/src/processor/burn/nonfungible_edition.rs
token-metadata/program/tests/burn.rs

Saves 480 bytes by moving edition derivation checks out of individual handlers to the common `burn.rs` file.

move edition derivation checks to common handler

---

token-metadata/program/src/processor/verification/collection_verification.rs

This reduces redundant code a bit. There might be a better refactor you see here, so feel free not to use this.
Amazingly, the binaries are the exact same size so this would only be beneficial for code readability, cleanliness, and maintainability.

reduce redundant code

---

auctioneer/program/Cargo.lock
auctioneer/program/src/execute_sale/mod.rs
auctioneer/program/tests/execute_sale.rs

Fixes errors when the creators of the nft are not the buyer or seller of a timed auction nft.
Closes:
- #922
- #852
- #786

Pass `remaining_accounts` to auction house properly

---

auction-house/program/src/utils.rs
auction-house/program/tests/execute_sale.rs
auctioneer/program/tests/execute_sale.rs

If one of the creators of an NFT has less than the rent exempt amount in their wallet, and the royalty from the sale is not enough to bring the balance over the rent exempt minimum then the sale will fail.
A workaround is to skip paying creator royalties unless they result in a valid balance for the creator wallet.

fix: Add Creator Minimum Balance Check

---

token-metadata/program/src/instruction/metadata.rs
token-metadata/program/src/processor/metadata/update.rs
token-metadata/program/src/state/metadata.rs

Use different `UpdateArgs` enum values for each delegate to control what fields can be updated.
Originally inspired by @samuelvanderwaal 's statement
> Defining these by negative fields feels a bit repetitive and perhaps easy to make a mistake. Is there a cleaner way to solve this with a HashSet of allow values for each type or something?
And thinking about type safety as a Rust idiom to solve this problem.

Use different UpdateArg types for different delegates

---

token-metadata/Cargo.lock
token-metadata/program/Cargo.toml

CI was failing to select a version of mpl-utils, and this is a fixup of that
```
Warning: cargo-build-bpf is deprecated. Please, use cargo-build-sbf
cargo-build-bpf child: /home/runner/.local/share/solana/install/active_release/bin/cargo-build-sbf --sbf-out-dir ../../test-programs/ --arch bpf
[2023-04-20T18:18:59.431506224Z ERROR cargo_build_sbf] Failed to obtain package metadata: `cargo metadata` exited with an error:     Updating crates.io index
Updating git repository `[https://github.com/metaplex-foundation/rooster`](https://github.com/metaplex-foundation/rooster%60)
error: failed to select a version for the requirement `mpl-utils = "^0.1.0"`
candidate versions found which didn't match: 0.2.0
location searched: /home/runner/actions-runner/_work/metaplex-program-library/metaplex-program …
```

Update mpl-utils in token-metadata

---

.github/actions/build-program/action.yml

Not sure how this was working prior to today because `RUST_STABLE` was not defined, which resulted in failures in my [`Update` PR](https://github.com/metaplex-foundation/metaplex-program-library/pull/1058).
Example of failing test run: https://github.com/metaplex-foundation/metaplex-program-library/actions/runs/4803372354/jobs/8552304748
This PR won't trigger the CI that uses it, but here's a passing run with this change applied on my PR branch:
https://github.com/metaplex-foundation/metaplex-program-library/actions/runs/4805994642/jobs/8552987442

Fix toolchain env variable name in action

---

token-metadata/js/test/create.test.ts
token-metadata/program/src/processor/metadata/create.rs

This PR enables setting the metadata value for `primary_sale_happened` on `create`.

Set primary sale happened value on create

---

token-metadata/program/src/processor/metadata/transfer.rs
token-metadata/program/src/utils/programmable_asset.rs

This PR removes log messages from the transfer instruction – the steps of the transfer can be inferred by the accounts and CPIs that are involved in the transaction.

Remove logs on transfer

---

token-metadata/js/idl/mpl_token_metadata.json
token-metadata/js/src/generated/types/UpdateArgs.ts
token-metadata/js/test/setup/txs-init.ts
token-metadata/js/test/update.test.ts
token-metadata/program/src/instruction/metadata.rs
token-metadata/program/src/processor/metadata/update.rs
token-metadata/program/src/state/metadata.rs
token-metadata/program/tests/update.rs

Wanted to add one ts test to use the `V2` update args.
Found I had missed an abbreviation change on `AsProgrammableConfigDelegateV2` so fixed that as well.

Add token-metadata Update ts test for V2 args

---

bubblegum/program/src/utils.rs

Previously in Bubblegum there was an injection of an additional creator during `decompress_v1`.  Added in [this commit](https://github.com/jarry-xiao/candyland/commit/4864f45fc1ec0f1a9a727c0d8b368ceab594c9cf#diff-0510c91bba2902bb7ddb233124c96ac8b9ca8b62f6b255dac2cac1225a9fc6ba) in Candyland July 2022.
Old Bubblegum code in Candyland repo:
```Rust
if metadata.creators.len() > 0 {
let mut amended_metadata_creators = metadata.creators;
amended_metadata_creators.push(Creator {
address: ctx.accounts.mint_authority.key(),
verified: true,
share: 0,
});
Some(
amended_metadata_creators
.iter()
.map(|c| c.adapt())
.collect(),
)
} else {
None
},
```
The reason for this injection of a creator was because in token-metadata there was a requirement that the metadata update authority had to be in the …

Allow for 5 creators in Bubblegum

---

token-metadata/program/src/error.rs
token-metadata/program/src/processor/delegate/delegate.rs
token-metadata/program/src/processor/delegate/revoke.rs

This PR fixes the error generated when a delegate record account is missing on `delegate` and `revoke` instructions.

Add missing delegate record error

---

token-metadata/Cargo.lock
token-metadata/program/src/instruction/mod.rs
token-metadata/program/src/processor/mod.rs
token-metadata/program/tests/deprecated_ixes.rs

To save binary space, deprecated instructions were removed from Token Metadata. However, to preserve ordering their enum variants were kept while their arguments were removed. This results in a Borsh deserialization error when a user passes in a removed instruction. This PR matches on Borsh deserialization errors for instructions and checks if the first byte of the data corresponds to the index of any of the deprecated instructions and returns a better error.

detect deprecated ixes and provide proper error

---

bubblegum/program/tests/simple.rs
bubblegum/program/tests/utils/context.rs
bubblegum/program/tests/utils/mod.rs
bubblegum/program/tests/utils/tree.rs
bubblegum/program/tests/utils/tx_builder.rs

* Changes the `Result` types in `tests/utils/mod.rs` to use `Box<Error>` for the error variant, to fix the clippy issue of large enum variant return.
* Removes use of `RefCell` for `Tree` and `TxBuilder` objects.  It looks like this was done to allow immutable references to be used for most method calls, and allow for immutable and mutable references to be used at the same time.
* Overall the use of `RefCell` was convenient but I don't think it is the best fit for this use case.  I'd rather just follow the borrow checker rules.  Also, it is not correct to hold a `RefCell` over await statements, which is fairly fundamental to the test architecture used here.
* For example, before this code change, a method such as `zero_leaf` would take an immutable reference to a `Tree` object instance, …

Removing remaining clippy errors from Bubblegum tests

---

token-metadata/program/src/processor/escrow/close_escrow_account.rs
token-metadata/program/src/processor/escrow/create_escrow_account.rs

The check was removed because it redundantly checked if you could close an account that can never be created do to the check in create.

Adding escrows for pNFTs and removing check for closing the account

---

token-metadata/program/ProgrammableNFTGuide.md

This PR adds the list of operation on Token Metadata that are subject to Token Authorization Rules.

Add operation list

---

bubblegum/js/.solitarc.js
bubblegum/js/package.json
bubblegum/js/src/mpl-bubblegum.ts
bubblegum/js/tests/main.test.ts
bubblegum/program/src/lib.rs

* These event logs are needed so that the indexer can get the leaf schemas for the assets being affected by these Bubblegum instructions and index them properly.
* Also add JS tests for transfer, burn, redeem and decompress.
* Also fix yarn API gen so Solita can build Anchor 0.26.0 the way cargo install does.
Note there is one warning when running the tests:
```
Transaction references a signature that is unnecessary, only the fee payer and instruction
signer accounts should sign a transaction. This behavior is deprecated and will throw an
error in the next major version release.
```
This is because the leaf owner is not marked as a Signer in the Anchor account validation struct.  It is only checked at runtime because either the leaf owner or the leaf delegate needs to be a signer but not …

Bubblegum add event log for burn, redeem, and decompress

---

token-metadata/program/src/processor/metadata/transfer.rs

Token Auth Rules v1.4 moved `cmp_pubkeys` to a different module which breaks this import in Token Metadata. We should be using the `cmp_pubkeys` from `mpl-utils` instead here for consistency anyway.
Token Auth Rules should also add the function back to the previous location as it shouldn't be making a public API change in a minor version release. Then patch release a v1.4.1 version with the `cmp_pubkeys` back in the `processor` module to fix anyone stuck on an older version of Token Metadata.
https://github.com/metaplex-foundation/metaplex-program-library/issues/1118
https://github.com/metaplex-foundation/mpl-token-auth-rules/issues/134

use cmp_pubkeys from mpl-utils instead of token auth rules

---

token-metadata/js/test/lock.test.ts
token-metadata/program/src/processor/state/mod.rs

This PR adds a check on the token account amount before allowing the account be locked/frozen. It also adds a test for locking an empty token account for `Fungible` asset type.

Add check for token amount on lock

---

token-metadata/program/src/processor/delegate/revoke.rs

PR to remove an unnecessary account being passed in on a cpi call to revoke a delegate.

Remove unnecessary account from cpi

---

bubblegum/program/src/lib.rs

This code was added to Bubblegum to make Read API indexing of compression easier.  But instead of using these leaf schema events, we were able to derive the `asset_id` using the leaf index from the change log event.
I think it would have been more convenient to use these leaf events, but by solving it through derivation in the Read API, it keeps the Read API backwards compatible with all existing cNFT transactions that don't provide the leaf schema events in `burn`, `redeem`, and `decompress`.
Note this code was never deployed to devnet or mainnet.

Reverting new leaf schema events for `burn`, `redeem`, and `decompress`

---

token-metadata/js/idl/mpl_token_metadata.json
token-metadata/js/src/generated/instructions/SetTokenStandard.ts
token-metadata/program/src/instruction/metadata.rs
token-metadata/program/src/instruction/mod.rs

This results in writable privilege escalation for e.g. when CPI-ing `SetTokenStandard` using anchor_spl with an immutable update_authority AccountInfo

Fix: set_token_standard() has update_authority unneccessarily set to mutable

---

token-metadata/program/src/processor/bubblegum/bubblegum_set_collection_size.rs

Removes a [redundant check](https://github.com/metaplex-foundation/metaplex-program-library/blob/d6f96f67b187104e6c4622b99f466bc530fc2b7d/bubblegum/program/src/lib.rs#L737C9-L737C9) that is already present in Bubblegum. As long as this handler is permissioned to Bubblegum this check only needs to be in Bubblegum. This assertion is[ getting reworked in Bubblegum to support both delegate types ](https://github.com/metaplex-foundation/metaplex-program-library/pull/1138) and it's not necessary to add the extra code to this assert as well--better to remove it to save binary size.

remove redundant check

---

token-metadata/js/idl/mpl_token_metadata.json
token-metadata/js/src/generated/errors/index.ts
token-metadata/program/src/error.rs

For this ticket I did a grep through all TM code for each error print name. If the only occurrence was in error.rs then I removed the text. Note: This will not catch any error prints used in macro expansion, but I believe the chance of that is minimal.

Removing Error prints that are not used

---

token-metadata/js/test/burn.test.ts
token-metadata/program/src/processor/burn/nonfungible.rs
token-metadata/program/src/processor/collection/unverify_collection.rs
token-metadata/program/src/processor/collection/unverify_sized_collection_item.rs
token-metadata/program/src/processor/verification/collection.rs
token-metadata/program/src/utils/mod.rs
token-metadata/program/tests/burn.rs
token-metadata/program/tests/burn_edition_nft.rs
token-metadata/program/tests/burn_nft.rs
token-metadata/program/tests/utils/digital_asset.rs

Currently, when burn handlers are called, if a metadata account has fees on it, the data length is reallocated to 0 but the ownership is not reassigned so that fees can be collected on the account. This PR changes the behavior to set the data length to 1 in this case and set that byte to 0 so that the discriminator is `Uninitialized`. This allows indexers to actually categorize and index these accounts until they are fully closed and garbage collected.
Note on the implementation:
```rust
if collection_metadata_info.data_is_empty()
|| collection_metadata_info.data.borrow()[0] == 0
```
Direct indexing panics if the index does not exist, but in this case it is ok to do because the if statement will short-circuit if the data is empty.

set burned metadata accounts with fees as Unitialized

---

token-metadata/program/src/processor/metadata/mint.rs
token-metadata/program/src/processor/metadata/print.rs
token-metadata/program/src/processor/metadata/transfer.rs

Removing assert_derivations for ATAs because the ATA program already does the derivation and will throw a missing account error if it's incorrect.

Remove duplicate derivation checks

---

core/rust/utils/Cargo.toml

When bumping `spl-token-2022` version on mpl-utils, the `default` feature was removed. This is not compatible with a patch version bump, creating problems for projects relying on the program crate. This PR restores the `default` feature.

Revert default feature

---

core/rust/utils/src/account.rs

added the possibility to return lamports after an account has been shrunk

Fix money returns caused by an account shrinking
